### PR TITLE
Syntax fixes for relative imports in Python3

### PR DESCRIPTION
**Pull request by hernando**

### CODE REVIEW

**Comment by apeyser** [comment]
Looks correct to me. See #204 -- is this a follow up on that, or independent? It looks like there were issues also with tests.

**Comment by apeyser** [comment]
@jougs, @tammoippen : anyone see a problem here?

**Comment by hernando** [comment]
This is independent of #204 (which I wasn't aware of). After building master with Python 3.4 I tried to import nest and it failed due to these broken imports.

**Comment by jougs** [comment]
@apeyser: this is a minimal version of #204.

I solved it exactly the same in https://github.com/jougs/nest-simulator/tree/split_pynest_hlapi earlier this week (see comment in #204). However, I also had to fix an additional problem with the `message` function of `NESTError`.

@hernando isn't that a problem for you? Did you try running `python -c "import nest; nest.test()"` with your patch?

As we got no reply from @prcastro yet and people are obviously hitting this regularly, I suggest, we either merge this (or my version if the problem with `NESTError` persists) rather soon.

**Comment by hernando** [comment]
nest.test() failed, but not with an import error. The relevant output was:

    ======================================================================
    ERROR: test_not_implemented_rules (nest.tests.test_sp.test_conn_builder.TestSPBuilder)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/gpfs/bbp.cscs.ch/home/hernando/local/modules/nest/2.10.0/lib/python3.4/site-packages/nest/tests/test_sp/test_conn_builder.py", line 78, in test_not_implemented_rules
        nest.Connect(neurons, neurons, conn_dict, syn_dict)
      File "/gpfs/bbp.cscs.ch/home/hernando/local/modules/nest/2.10.0/lib/python3.4/site-packages/nest/lib/hl_api_helper.py", line 142, in stack_checker_func
        result = f(*args, **kwargs)
      File "/gpfs/bbp.cscs.ch/home/hernando/local/modules/nest/2.10.0/lib/python3.4/site-packages    /nest/lib/hl_api_connections.py", line 478, in Connect
        sr('Connect')
      File "/gpfs/bbp.cscs.ch/home/hernando/local/modules/nest/2.10.0/lib/python3.4/site-packages/nest/__init__.py", line 85, in catching_sli_run
        raise _kernel.NESTError("{0} in {1}{2}".format(errorname, commandname, message))
    pynestkernel.NESTError: NotImplemented in Connect_g_g_D_D: This connection rule is not implemented for structural plasticity

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/gpfs/bbp.cscs.ch/home/hernando/local/modules/nest/2.10.0/lib/python3.4/site-packages/nest/tests/test_sp/test_conn_builder.py", line 80, in test_not_implemented_rules
        self.assertRegexpMatches(e.message, 'This connection rule is not implemented for structural plasticity')
    AttributeError: 'NESTError' object has no attribute 'message'

Commit 79405ce is the same. From #204 I think that the change in  pynest/nest/tests/test_sp/test_conn_builder.py:80 is also required. I wouldn't merge the changes in #204 that convert relative imports into absolute ones.

**Comment by jougs** [comment]
NEST Core decided to accept this PR and merge immediately and close #204.

**Pull request merged**
