### PR TITLE
Fix Vera++ issues in some core files and disable rule T011

### PR DESCRIPTION
**Pull request by heplesser**
This PR disables Vera++ rule T011 (curly braces check), since it becomes confused by some conditional code inclusion, e.g.,
```C++
#ifdef _OPENMP
#pragma omp parallel reduction( + : num_active_nodes, num_active_wfr_nodes )
  {
    size_t t = kernel().vp_manager.get_thread_id();
#else
    for ( index t = 0; t < kernel().vp_manager.get_num_threads(); ++t )
    {
#endif
    ...
  } // end of parallel section / end of for threads
``` 
Vera++ counts this as two opening and just one closing brace. Doubling the closing brace in a preprocessor conditional would reduce code legibility just to satisfy Vera++.

Disabling braces checking in Vera++ seems little problematic, since clang-format will check indentation and the compiler will check that each opening brace has a closing one.

The PR also fixes Vera++ issues in some core files.

**Note:** When this PR is merged, send a message to NEST User to remind everyone to install the updated `extras/vera++.profile` file as `.../lib/vera++/profiles/nest`.

### CODE REVIEW

**Comment by hakonsbm** [comment]
I am working on more Vera++ fixes that will be merged into this branch in the next couple hours.

**Comment by apeyser** [comment]
@hakonsbm Make it another PR - we should try to keep PRs as simple as possible.

**Comment by apeyser** [comment]
This is going to cause a massive problem for all merges now.

**Comment by apeyser** [comment]
And what process was used precisely to make these changes?

**Comment by heplesser** [comment]
@apeyser We (@jougs, @gtrensch, @hakonsbm, @stinebuu. @terhorstd, @heplesser) are currently working through all files fixing the Vera issues in one big go. We hope to be done within an hour or two, so this will turn into the "fix all Vera issues" PR.

**Comment by apeyser** [comment]
Is there an issue number discussing the merge implications of "fix all Vera issues"? This is a seriously problematic approach.

**Comment by heplesser** [comment]
@apeyser We decided to postpone these changes, so I close this PR (for now).

**Pull request closed without merging**
