### PR TITLE
Rename PyNEST microcircuit example titles

### LINKED ISSUE #1650: Enhance PyNEST microcircuit example documentation
Following the merge of #1526, this issue addresses further enhancements to the PyNEST microcircuit example:

- [x] Rename titles to "Cortical microcircuit example" -> #1841 
- [x] Update "Note on Parameters" subheading -> #1841 
- [x] Update links to files in ``pynest/examples/Potjans_2014`` -> #1847 
- [ ] Automatically generate parameter table out of ``network_params.py``

### PR DESCRIPTION
**Pull request by sarakonradi**
This PR updates the PyNEST microcircuit example documentation by:

- renaming "Microcircuit example" to "Cortical microcircuit example";
- changing "PyNEST microcircuit" to "Cortical microcircuit model"; and
- writing "External drive and conditions" instead of "Note on parameters".

### CODE REVIEW

**Review by steffengraber — COMMENTED** [review]
What's about the `.py` files inside `.../pynest/examples/Potjans_2014`? The text there is also part of the documentation.
Or is that just left out for now?

**Comment by sarakonradi** [comment]
> What's about the `.py` files inside `.../pynest/examples/Potjans_2014`? The text there is also part of the documentation.
> Or is that just left out for now?

I think we already addressed that in #1526, where we created a new landing page with  clickable links to the ``.py`` files. Or are you referring to something else?

**Comment by sarakonradi** [comment]
We discussed this at the NEST Hackathon and agreed on focusing on the titles in this PR. The links will be addressed in a separate issue (#1847).

**Comment by terhorstd** [comment]
Jointly reviewed at hackathon.

**Pull request merged**
