### PR TITLE
First Structural Plasticity Pull request, corrected

### PR DESCRIPTION
**Pull request by sdiazpier**
These changes include the first step in order to enable structural plasticity in NEST. The implementation corresponds to the formalism described in: M. Butz and A. van Ooyen. A simple rule for dendritic spine and axonal bouton formation can account for cortical reorganization after focal retinal lesions. PLoS Comput. Biol., 9(10):e1003259, Oct 2013.

This Model of Structural Plasticity (MSP) considers synapses to be not just a weighted link between two neurons but as consisting of two connected parts, a presynaptic axonal element and a postsynaptic dendritic element. Matching synaptic elements develop independently from each other, only depending on the level of activity of the hosting neuron.
Once new synaptic elements are formed, they are first considered as vacant. From that moment on, they can be connected with a matching counterpart to form a new synapse in a random process.
Synapses can break apart when a bound synaptic element is deleted. The remaining and now freed synaptic element of the broken synapse can then rebind with a different synaptic element.
Breaking of synapses and rebinding of synaptic elements causes the rewiring of the network until a homoeostatic point is reached.

This first request includes only the implementation of classes and data structures to represent synaptic elements and their dynamics within the network. No changes in the connectivity are present at this point.

### CODE REVIEW

**Comment by apeyser** [comment]
Could you nominate some reviewers? Just mention them here by saying something like "I think @sdiazpier would be good to review this". So @ + github handle. That way they'll get a notification directed to them, and they will hopefully volunteer.

**Comment by sdiazpier** [comment]
Given the type of changes included in this branch (mainly in the nest kernel), I think @jougs, @apeyser and/or @wschenck would be good to review this. 

Thank you.

**Comment by apeyser** [comment]
@sdiazpier: I believe that's all the comments I have here, it's mostly lint and questions.

**Comment by naveau** [comment]
Thx @apeyser ! I'll help @sdiazpier to answer your comments. Unfortunately, I don't have a proper workstation to correct and test the code yet (I'm "working" on a very old MacBook and I don't want to commit myself into installing NEST on it!).

**Comment by sdiazpier** [comment]
@apeyser Thank you very much for taking the time to review our code. I will check your comments one by one with @naveau and make any necessary modifications. @naveau don't worry I can make the corrections on my computer.

**Comment by tammoippen** [comment]
You often have no braces around blocks of code in control structures (see [Coding Guidelines](https://nest.github.io/nest-simulator/coding_guidelines_c++#further-indentation-and-formatting) ):
archiving_node.cpp:247ff, 316, 
synaptic_element.cpp:71, 129, 245

**Pull request closed without merging**
