### PR TITLE
Fix issue #141: Error with non default tics_per_ms

### PR DESCRIPTION
**Pull request by frankmichler**
When compiled with --with-tics-per-ms=4 --with-tics-per-step=1, on NEST import an error occurs in constructor of node class "correlospinmatrix_detector".

"The default resolution of 0.25 ms (= 1 tics = 1 step) is not consistent with the value
0 ms (= 0 tics = 0 steps) of property 'delta_tau' in model UnknownNode."

### CODE REVIEW

**Comment by jougs** [comment]
@frankmichler: Thanks for your contribution!

Here's just a short word on the procedure: one of the NEST core developers will have a look at this pull request soon and we'll come back to you after a review. It is not a problem at this time if checks fail. You don't have to close the request, but instead you can add new commits to your branch in order to fix problems or reply to comments by the reviewers.

**Comment by frankmichler** [comment]
I closed pull request #142 because I realized that the solution was wrong. 
```
NEST Testsuite Summary
----------------------
  NEST Executable: /home/travis/build/nest/nest-simulator/result/bin/nest
  SLI Executable : /home/travis/build/nest/nest-simulator/result/bin/sli
  Total number of tests: 199
     Passed: 76
     Failed: 123 
```
So I deleted the branch, and created it new with the solution I think is correct.
Now pull request #144  tests are passing:

```
NEST Testsuite Summary
----------------------
  NEST Executable: /home/travis/build/nest/nest-simulator/result/bin/nest
  SLI Executable : /home/travis/build/nest/nest-simulator/result/bin/sli
  Total number of tests: 199
     Passed: 199
     Failed: 0 
```

But the Travis build failes because of a log parsing error:

```
The command "python extras/parse_travis_log.py build.sh.log" exited with 1.
```

But good to know that next time I should make my corrections by just adding a new commit instead of deleting and recreating branch and pull request.

**Comment by jougs** [comment]
@mhelias: can you please have a look at this? Especially, I am afraid that the division in the proposed solution can lead to nasty side effects.

**Comment by frankmichler** [comment]
@jougs: what kind of side effects do you mean? There are only two things that come to my mind:
1. division by zero
2. accidental integer division with result zero

Both things are safe in this case:
1. Time::get_tics_per_ms() should never return zero. If someone configured "--with-tics-per-ms=0" I can't imagine that anything works at all.
2.  Time::get_tics_per_ms() returns an integer type. So there is cause to worry. But Time::get_tics_per_ms() has return type double_t. So the division should always be performed as an floating point division.

And in the default case, the result should be the same as before, because nest_time.cpp defines:
```cpp
#ifndef HAVE_TICS_PER_MS
#define CONFIG_TICS_PER_MS 1000.0
#endif

#ifndef HAVE_TICS_PER_STEP
#define CONFIG_TICS_PER_STEP 100
#endif
```

The result should be 0.1, which is the same as the literal "0.1" which is in the current code.
Am I missing something important here?

**Comment by heplesser** [comment]
@frankmichler @jougs @mhelias The documentation states that `delta_tau` must be a multiple of the resolution, and the old default is just the resolution, but hard-coded as `0.1`, which is the resolution in the default case. The correct way to introduce it into the constructor is
```C++
delta_tau_( Time::get_resolution() )
```
This will always work and we need not worry about any side effects.

Similar issues occur in `correlomatrix_detector`, where the doc states that `delta_tau` has to be an odd multiple of the resolution, and `0.5` is hardcoded. I'd suggest
```C++
delta_tau_( 5 * Time::get_resolution() )
```

Finally, `correlation_detector` has
```C++
delta_tau_( Time::ms(1.0) )
```
I would argue for leaving that as it is---anyone choosing a time base that cannot represent 1 ms is in a state of sin.

@mhelias Any additional thoughts?

**Comment by jougs** [comment]
@mhelias likes the change. Thus merging.

**Pull request merged**
