### PR TITLE
Update to fix C++11 compilation error

### LINKED ISSUE #220: Build error on Fedora rawhide (what will become Fedora 24 - GCC 6)
This is what I get when trying to build nest using my rpm on Fedora rawhide (24). It builds perfectly on Fedora 23. The one major different between Fedora 23 and rawhide/24 is that rawhide/24 is now using GCC 6 for builds, while F23 is using GCC 5.3.1

```
listartup.cc:81:15: error: cannot convert 'std::ifstream {aka std::basic_ifstream<char>}' to 'bool' in return
   return ( in );
               ^
```

Complete build log files can be found here: https://ankursinha.fedorapeople.org/misc/nest-rawhide-logs/

### PR DESCRIPTION
**Pull request by sanjayankur31**
This seems to be the only one at the moment. Fixes #220

System info:
``` bash
$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/6.1.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap
--enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr
--mandir=/usr/share/man --infodir=/usr/share/info
--with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared
--enable-threads=posix --enable-checking=release --enable-multilib
--with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions
--enable-gnu-unique-object --enable-linker-build-id
--with-linker-hash-style=gnu --enable-plugin --enable-initfini-array
--disable-libgcj --with-isl --enable-libmpx
--enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686
--build=x86_64-redhat-linux
Thread model: posix
gcc version 6.1.1 20160510 (Red Hat 6.1.1-2) (GCC)

$ cat /etc/os-release
NAME=Fedora
VERSION="24 (Workstation Edition)"
```

### CODE REVIEW

**Comment by sanjayankur31** [comment]
@jougs - can you please review this when you have the time? Cheers :)

**Comment by heplesser** [comment]
:+1: from me. Before merging, though, I would like Travis to double check this one, but that will require #380 to be fixed.

**Comment by sanjayankur31** [comment]
Would you know how I could kick off a fresh travis build for this without pushing a dummy commit?

**Comment by sanjayankur31** [comment]
Ah, I'll just merge this with master and push it. Should do the trick.

**Comment by sanjayankur31** [comment]
The build is failing with a format error, but when I run the ./format_all_c_c++_files.sh script, it doesn't make any changes as the output below shows.  Not sure what's causing this now. 

``` bash
[asinha@cs-as14aho-2-herts-ac-uk  nest-simulator(C++11-fix=)]$ CLANG_FORMAT=~/dump/clang+llvm-3.6.0-x86_64-fedora21/bin/clang-format ./extras/format_all_c_c++_files.sh sli/
Process directory: sli/
 - Format C/C++ file: sli//aggregatedatum.h
 - Format C/C++ file: sli//allocator.cpp
 - Format C/C++ file: sli//allocator.h
 - Format C/C++ file: sli//arraydatum.cc
 - Format C/C++ file: sli//arraydatum.h
 - Format C/C++ file: sli//booldatum.cc
 - Format C/C++ file: sli//booldatum.h
 - Format C/C++ file: sli//callbackdatum.h
 - Format C/C++ file: sli//charcode.cc
 - Format C/C++ file: sli//charcode.h
 - Format C/C++ file: sli//datum.cc
 - Format C/C++ file: sli//datum.h
 - Format C/C++ file: sli//dict.cc
 - Format C/C++ file: sli//dictdatum.cc
 - Format C/C++ file: sli//dictdatum.h
 - Format C/C++ file: sli//dict.h
 - Format C/C++ file: sli//dictstack.cc
 - Format C/C++ file: sli//dictstack.h
 - Format C/C++ file: sli//dictutils.cc
 - Format C/C++ file: sli//dictutils.h
 - Format C/C++ file: sli//doubledatum.cc
 - Format C/C++ file: sli//doubledatum.h
 - Format C/C++ file: sli//fdstream.cc
 - Format C/C++ file: sli//fdstream.h
 - Format C/C++ file: sli//filesystem.cc
 - Format C/C++ file: sli//filesystem.h
 - Format C/C++ file: sli//functional.h
 - Format C/C++ file: sli//functiondatum.cc
 - Format C/C++ file: sli//functiondatum.h
 - Format C/C++ file: sli//genericdatum.h
 - Format C/C++ file: sli//get_mem.c
 - Format C/C++ file: sli//gnureadline.cc
 - Format C/C++ file: sli//gnureadline.h
 - Format C/C++ file: sli//integerdatum.cc
 - Format C/C++ file: sli//integerdatum.h
 - Format C/C++ file: sli//interpret.cc
 - Format C/C++ file: sli//interpret.h
 - Format C/C++ file: sli//iostreamdatum.cc
 - Format C/C++ file: sli//iostreamdatum.h
 - Format C/C++ file: sli//iteratordatum.cc
 - Format C/C++ file: sli//iteratordatum.h
 - Format C/C++ file: sli//literaldatum.cc
 - Format C/C++ file: sli//lockptrdatum.h
 - Format C/C++ file: sli//lockptrdatum_impl.h
 - Format C/C++ file: sli//name.cc
 - Format C/C++ file: sli//namedatum.cc
 - Format C/C++ file: sli//namedatum.h
 - Format C/C++ file: sli//name.h
 - Format C/C++ file: sli//numericdatum.h
 - Format C/C++ file: sli//numericdatum_impl.h
 - Format C/C++ file: sli//oosupport.cc
 - Format C/C++ file: sli//oosupport.h
 - Format C/C++ file: sli//parser.cc
 - Format C/C++ file: sli//parserdatum.h
 - Format C/C++ file: sli//parser.h
 - Format C/C++ file: sli//processes.cc
 - Format C/C++ file: sli//processes.h
 - Format C/C++ file: sli//psignal.c
 - Format C/C++ file: sli//psignal.h
 - Format C/C++ file: sli//puresli.cc
 - Format C/C++ file: sli//scanner.cc
 - Format C/C++ file: sli//scanner.h
 - Format C/C++ file: sli//sliactions.cc
 - Format C/C++ file: sli//sliactions.h
 - Format C/C++ file: sli//sliarray.cc
 - Format C/C++ file: sli//sliarray.h
 - Format C/C++ file: sli//slibuiltins.cc
 - Format C/C++ file: sli//slibuiltins.h
 - Format C/C++ file: sli//slicontrol.cc
 - Format C/C++ file: sli//slicontrol.h
 - Format C/C++ file: sli//slidata.cc
 - Format C/C++ file: sli//slidata.h
 - Format C/C++ file: sli//slidict.cc
 - Format C/C++ file: sli//slidict.h
 - Format C/C++ file: sli//sliexceptions.cc
 - Format C/C++ file: sli//sliexceptions.h
 - Format C/C++ file: sli//slifunction.h
 - Format C/C++ file: sli//sligraphics.cc
 - Format C/C++ file: sli//sligraphics.h
 - Format C/C++ file: sli//sli_io.cc
 - Format C/C++ file: sli//sli_io.h
 - Format C/C++ file: sli//slimath.cc
 - Format C/C++ file: sli//slimath.h
 - Format C/C++ file: sli//slimodule.cc
 - Format C/C++ file: sli//slimodule.h
 - Format C/C++ file: sli//slinames.cpp
 - Format C/C++ file: sli//slinames.h
 - Format C/C++ file: sli//sliregexp.cc
 - Format C/C++ file: sli//sliregexp.h
 - Format C/C++ file: sli//slistack.cc
 - Format C/C++ file: sli//slistack.h
 - Format C/C++ file: sli//slistartup.cc
 - Format C/C++ file: sli//slistartup.h
 - Format C/C++ file: sli//slitype.cc
 - Format C/C++ file: sli//slitypecheck.cc
 - Format C/C++ file: sli//slitypecheck.h
 - Format C/C++ file: sli//slitype.h
 - Format C/C++ file: sli//specialfunctionsmodule.cc
 - Format C/C++ file: sli//specialfunctionsmodule.h
 - Format C/C++ file: sli//stringdatum.cc
 - Format C/C++ file: sli//stringdatum.h
 - Format C/C++ file: sli//symboldatum.cc
 - Format C/C++ file: sli//symboldatum.h
 - Format C/C++ file: sli//tarrayobj.cc
 - Format C/C++ file: sli//tarrayobj.h
 - Format C/C++ file: sli//tokenarray.cc
 - Format C/C++ file: sli//tokenarray.h
 - Format C/C++ file: sli//token.cc
 - Format C/C++ file: sli//token.h
 - Format C/C++ file: sli//tokenstack.cc
 - Format C/C++ file: sli//tokenstack.h
 - Format C/C++ file: sli//tokenutils.cc
 - Format C/C++ file: sli//tokenutils.h
 - Format C/C++ file: sli//triedatum.cc
 - Format C/C++ file: sli//triedatum.h
 - Format C/C++ file: sli//typearray.h
 - Format C/C++ file: sli//typechk.cc
 - Format C/C++ file: sli//typechk.h
 - Format C/C++ file: sli//utils.cc
 - Format C/C++ file: sli//utils.h

asinha@cs-as14aho-2-herts-ac-uk  nest-simulator(C++11-fix=)]$ git diff
[asinha@cs-as14aho-2-herts-ac-uk  nest-simulator(C++11-fix=)]$ 

```

Also used the same binary that the build.sh script is using:
``` bash
[asinha@cs-as14aho-2-herts-ac-uk  nest-simulator(C++11-fix=)]$ CLANG_FORMAT=~/dump/clang+llvm-3.6.0-x86_64-linux-gnu/bin/clang-format ./extras/format_all_c_c++_files.sh sli/

Process directory: sli/
 - Format C/C++ file: sli//aggregatedatum.h
 - Format C/C++ file: sli//allocator.cpp
 - Format C/C++ file: sli//allocator.h
 - Format C/C++ file: sli//arraydatum.cc
 - Format C/C++ file: sli//arraydatum.h
 - Format C/C++ file: sli//booldatum.cc
 - Format C/C++ file: sli//booldatum.h
 - Format C/C++ file: sli//callbackdatum.h
 - Format C/C++ file: sli//charcode.cc
 - Format C/C++ file: sli//charcode.h
 - Format C/C++ file: sli//datum.cc
 - Format C/C++ file: sli//datum.h
 - Format C/C++ file: sli//dict.cc
 - Format C/C++ file: sli//dictdatum.cc
 - Format C/C++ file: sli//dictdatum.h
 - Format C/C++ file: sli//dict.h
 - Format C/C++ file: sli//dictstack.cc
 - Format C/C++ file: sli//dictstack.h
 - Format C/C++ file: sli//dictutils.cc
 - Format C/C++ file: sli//dictutils.h
 - Format C/C++ file: sli//doubledatum.cc
 - Format C/C++ file: sli//doubledatum.h
 - Format C/C++ file: sli//fdstream.cc
 - Format C/C++ file: sli//fdstream.h
 - Format C/C++ file: sli//filesystem.cc
 - Format C/C++ file: sli//filesystem.h
 - Format C/C++ file: sli//functional.h
 - Format C/C++ file: sli//functiondatum.cc
 - Format C/C++ file: sli//functiondatum.h
 - Format C/C++ file: sli//genericdatum.h
 - Format C/C++ file: sli//get_mem.c
 - Format C/C++ file: sli//gnureadline.cc
 - Format C/C++ file: sli//gnureadline.h
 - Format C/C++ file: sli//integerdatum.cc
 - Format C/C++ file: sli//integerdatum.h
 - Format C/C++ file: sli//interpret.cc
 - Format C/C++ file: sli//interpret.h
 - Format C/C++ file: sli//iostreamdatum.cc
 - Format C/C++ file: sli//iostreamdatum.h
 - Format C/C++ file: sli//iteratordatum.cc
 - Format C/C++ file: sli//iteratordatum.h
 - Format C/C++ file: sli//literaldatum.cc
 - Format C/C++ file: sli//lockptrdatum.h
 - Format C/C++ file: sli//lockptrdatum_impl.h
 - Format C/C++ file: sli//name.cc
 - Format C/C++ file: sli//namedatum.cc
 - Format C/C++ file: sli//namedatum.h
 - Format C/C++ file: sli//name.h
 - Format C/C++ file: sli//numericdatum.h
 - Format C/C++ file: sli//numericdatum_impl.h
 - Format C/C++ file: sli//oosupport.cc
 - Format C/C++ file: sli//oosupport.h
 - Format C/C++ file: sli//parser.cc
 - Format C/C++ file: sli//parserdatum.h
 - Format C/C++ file: sli//parser.h
 - Format C/C++ file: sli//processes.cc
 - Format C/C++ file: sli//processes.h
 - Format C/C++ file: sli//psignal.c
 - Format C/C++ file: sli//psignal.h
 - Format C/C++ file: sli//puresli.cc
 - Format C/C++ file: sli//scanner.cc
 - Format C/C++ file: sli//scanner.h
 - Format C/C++ file: sli//sliactions.cc
 - Format C/C++ file: sli//sliactions.h
 - Format C/C++ file: sli//sliarray.cc
 - Format C/C++ file: sli//sliarray.h
 - Format C/C++ file: sli//slibuiltins.cc
 - Format C/C++ file: sli//slibuiltins.h
 - Format C/C++ file: sli//slicontrol.cc
 - Format C/C++ file: sli//slicontrol.h
 - Format C/C++ file: sli//slidata.cc
 - Format C/C++ file: sli//slidata.h
 - Format C/C++ file: sli//slidict.cc
 - Format C/C++ file: sli//slidict.h
 - Format C/C++ file: sli//sliexceptions.cc
 - Format C/C++ file: sli//sliexceptions.h
 - Format C/C++ file: sli//slifunction.h
 - Format C/C++ file: sli//sligraphics.cc
 - Format C/C++ file: sli//sligraphics.h
 - Format C/C++ file: sli//sli_io.cc
 - Format C/C++ file: sli//sli_io.h
 - Format C/C++ file: sli//slimath.cc
 - Format C/C++ file: sli//slimath.h
 - Format C/C++ file: sli//slimodule.cc
 - Format C/C++ file: sli//slimodule.h
 - Format C/C++ file: sli//slinames.cpp
 - Format C/C++ file: sli//slinames.h
 - Format C/C++ file: sli//sliregexp.cc
 - Format C/C++ file: sli//sliregexp.h
 - Format C/C++ file: sli//slistack.cc
 - Format C/C++ file: sli//slistack.h
 - Format C/C++ file: sli//slistartup.cc
 - Format C/C++ file: sli//slistartup.h
 - Format C/C++ file: sli//slitype.cc
 - Format C/C++ file: sli//slitypecheck.cc
 - Format C/C++ file: sli//slitypecheck.h
 - Format C/C++ file: sli//slitype.h
 - Format C/C++ file: sli//specialfunctionsmodule.cc
 - Format C/C++ file: sli//specialfunctionsmodule.h
 - Format C/C++ file: sli//stringdatum.cc
 - Format C/C++ file: sli//stringdatum.h
 - Format C/C++ file: sli//symboldatum.cc
 - Format C/C++ file: sli//symboldatum.h
 - Format C/C++ file: sli//tarrayobj.cc
 - Format C/C++ file: sli//tarrayobj.h
 - Format C/C++ file: sli//tokenarray.cc
 - Format C/C++ file: sli//tokenarray.h
 - Format C/C++ file: sli//token.cc
 - Format C/C++ file: sli//token.h
 - Format C/C++ file: sli//tokenstack.cc
 - Format C/C++ file: sli//tokenstack.h
 - Format C/C++ file: sli//tokenutils.cc
 - Format C/C++ file: sli//tokenutils.h
 - Format C/C++ file: sli//triedatum.cc
 - Format C/C++ file: sli//triedatum.h
 - Format C/C++ file: sli//typearray.h
 - Format C/C++ file: sli//typechk.cc
 - Format C/C++ file: sli//typechk.h
 - Format C/C++ file: sli//utils.cc
 - Format C/C++ file: sli//utils.h
[asinha@cs-as14aho-2-herts-ac-uk  nest-simulator(C++11-fix=)]$ git diff
[asinha@cs-as14aho-2-herts-ac-uk  nest-simulator(C++11-fix=)]$ 
```

Makes no difference.

**Comment by sanjayankur31** [comment]
Not a formatting error any more - something wrong with `parse_travis_log.py`. 

``` bash
Built target installcheck
+[ x != x ]
+[ 389 != false ]
+echo WARNING: Not uploading results as this is a pull request
WARNING: Not uploading results as this is a pull request
+exit 0

The command "./build.sh 2>&1 | tee build.sh.log" exited with 0.

$ python extras/parse_travis_log.py build.sh.log

--------<<<<<<<< Summary of TravisCI >>>>>>>>--------
Vera init:           Ok
Cppcheck init:       Ok
Changed files:       False
Traceback (most recent call last):
  File "extras/parse_travis_log.py", line 361, in <module>
    for i in static_analysis.itervalues()]) else "Error"))
KeyError: 'clang-format'

The command "python extras/parse_travis_log.py build.sh.log" exited with 1.
Done. Your build exited with 1.
```

**Comment by sanjayankur31** [comment]
I see this is already reported here: https://github.com/nest/nest-simulator/pull/391

**Comment by heplesser** [comment]
@sanjayankur31 I am working on fixing our Travis scripts, please wait until #391 is merged before you try again. Briefly, the problem was that our source for the clang-format program became unavailable. #380 fixed that, but under certain conditions the results were not parsed properly. #391 will fix that. Until then, our Travis setup does not work reliably.

**Pull request merged**
