### PR TITLE
Correct rounding of synaptic delays in the cortical microcircuit examples

### PR DESCRIPTION
**Pull request by gtrensch**
This pull request resolves issue #2503.
 
The changes applied by this pull request, slightly change the behavior of the cortical microcircuit (see #2503). It should therefore be discussed whether this is desired or not.

### CODE REVIEW

**Review by jhnnsnk — COMMENTED** [review]
Well spotted! I think that this is the expected behavior and therefore we should update the model as suggested.
On the long run, one could consider of making this default for redrawing - what do you think?
I would suggest two small additions to this PR:
1. Could you please update the new firing rates in the [code](https://github.com/nest/nest-simulator/blob/8c386cec300b3369cfc798c59eee7e33f8cca16e/pynest/examples/Potjans_2014/network_params.py#L76) as they are used for downscaling?
2. To make the documentation clearer (see #2452), I would suggest to mention there that this effect not only appears for the uniform distribution but also for the normal distribution.

**Comment by gtrensch** [comment]
I've adjusted the mean rates and also added a sentence to the documentation. Please review again.

**Review by heplesser — APPROVED** [review]
I think this is a good fix.

**Comment by gtrensch** [comment]
I also updated the reference data.

**Review by heplesser — APPROVED** [review]

**Pull request merged**
