### PR TITLE
Add a catch clause for std::bad_alloc exception

### PR DESCRIPTION
**Pull request by pnbabu**

### CODE REVIEW

**Comment by pnbabu** [comment]
Fixes #1891

**Comment by clinssen** [comment]
Some initial observations:

- ``import nest; nest.Create("iaf_psc_exp", 1000000000)`` reliably triggers the exception.

- There is ``SLIInterpreter::execute_()`` and ``SLIInterpreter::execute_debug_()``. Your patch is only for the latter; please apply it also to the former.

- In these methods, there is a nested try..catch block, and the bad_alloc exception seems to come from the inner block, and is not re-thrown to be caught by the outer block. Thus, it looks like the bad_alloc catch should also be in the inner block, that is to say, here: https://github.com/nest/nest-simulator/blob/c2bd9d970927744e2c557e98aa81e153a032821c/sli/interpret.cc#L1291

**Comment by heplesser** [comment]
This will be useful for Linux, even if corresponding errors are not caught on macOS because of a different approach to handling excess memory requests.

**Comment by pnbabu** [comment]
@heplesser I agree that it would be useful for Linux, but as mentioned [here](https://github.com/nest/nest-simulator/issues/1891#issuecomment-772610925), the exception thrown is of the type `std::exception` and not `std::bad_alloc`, and the former is already caught and handled in the code. Since the specific exception, `std::bad_alloc` is not thrown, adding a specific catch block for it will not help. Instead, we could document this error somewhere. Do you have any other ideas?

**Comment by clinssen** [comment]
I propose to close this PR, as we already have issue #1891 open, and the conclusion was drawn there that it should be a documentation update rather than a code update.

**Comment by jougs** [comment]
@clinssen: I agree with you and will thus close this issue. @pnbabu: many thanks again for your investigations and work!

**Pull request closed without merging**
