### PR TITLE
Replacing internal C++ variable U0_ by E_L.

### PR DESCRIPTION
**Pull request by jougs**
Most neuron models use the internal variable `U0_` for the resting potential. The user interface uses the name `E_L` to conform to our policy of using Dyan&Abbot terminology wherever possible.

This is confusing and this pull request replaces `U0_` by `E_L_` and thus makes code, comments and UI wording consistent.

I suggest @heplesser and @tammoippen as reviewers.

### CODE REVIEW

**Comment by tammoippen** [comment]
:+1:  from my side! Nice. Do you think, we need to adjust the examples as well? There `U0` is used a lot as a local variable.

**Comment by jougs** [comment]
Yes, probably we should also change the examples. I'll look into this.

**Comment by heplesser** [comment]
@jougs This seems to make a lot of sense. I trust no U0 is left in the code now? Have you run all the examples to make sure that everything still works?

**Comment by jougs** [comment]
@heplesser: I can confirm that U0 is gone from NEST completely. I've also run all examples using the `run_examples.sh` script provided in the `examples` directory and did not observe any problems.

**Comment by heplesser** [comment]
:+1: then for a U0-free world! Any U2 in NEST ;)?

**Pull request merged**
