### PR TITLE
Update Python version check in __init__.py to check for minor version, and to report correct minimum required version (>= 3.8)

### PR DESCRIPTION
**Pull request by niltonlk**
As commented on #2122, remove Python version check in `__init__.py` as minimum requirement is already enforced to be >= 3.8 (#1954)

### CODE REVIEW

**Comment by niltonlk** [comment]
When runtime version is older than compiletime, besides the RuntimeWarning, import of NEST also fails and execution aborts.
In the opposite situation, when compiletime version is older than runtime, the RuntimeWarning is also displayed but import succeeds.
I have updated the check for exact match with the following Exception message:
Python runtime version does not match 'nest' complietime version. Please use Python @Python_VERSION_MAJOR@.@Python_VERSION_MINOR@.

**Review by Helveg — APPROVED** [review]
Very good! This should help people detect when they are loading incorrect NEST/Python versions :)

Unless there are any devs that want to explicitly make loading NEST with different versions of Python a possibility, but then the aforementioned ABI flag should be checked and documented (perhaps it already is).

**Review by clinssen — APPROVED** [review]
Great, thank you!

**Comment by Helveg** [comment]
@clinssen won't the docs break if the source dir doesn't contain `.py` files but `.py.in` files, from `doc/userdoc/conf.py`:

```python
source_dir = os.environ.get('NESTSRCDIR', False)
if source_dir:
    source_dir = Path(source_dir)
else:
    source_dir = Path(__file__).resolve().parent.parent.parent.resolve()


if os.environ.get("READTHEDOCS") == "True":
    doc_build_dir = source_dir / "doc/userdoc"
else:
    doc_build_dir = Path(os.environ["OLDPWD"]) / "doc/userdoc"

print("doc_build_dir", str(doc_build_dir))
print("source_dir", str(source_dir))

source_suffix = '.rst'
master_doc = 'contents'

# Create the mockfile for extracting the PyNEST

excfile = source_dir / "pynest/nest/lib/hl_api_exceptions.py"
infile = source_dir / "pynest/pynestkernel.pyx"
outfile = doc_build_dir / "pynestkernel_mock.py"

sys.path.insert(0, str(source_dir))
sys.path.insert(0, str(source_dir / 'doc'))
sys.path.insert(0, str(source_dir / 'pynest'))
sys.path.insert(0, str(source_dir / 'pynest/nest'))
sys.path.insert(0, str(doc_build_dir))
```

**Comment by niltonlk** [comment]
I am not sure about the doc part. How can I check if there are problems with this PR regarding @Helveg last comment? At least `make doc` and `make fulldoc` also resulted in no errors.

**Comment by Helveg** [comment]
There currently should not be a problem, but in an upcoming PR (#2114) exactly the `__init__.py` that you modified is undergoing changes and will be used for the doc, we might notice problems then, so let's wait for it to be merged and I will check the impact on the docs for you!

**Comment by niltonlk** [comment]
Got it! Thank you!

**Pull request merged**
