### PR TITLE
Wrong comparison operator for connections using parameter arrays

### PR DESCRIPTION
**Pull request by hannahbos**
Changed the comparison operator checking the dimensionality of parameter arrays from 'is not' to !=. This caused problems for larger arrays since 'is not' compares the identity of objects (which appears to be fixed in Python for integers ranging from -5 to 256) rather than their value. @heplesser @jougs

### CODE REVIEW

**Comment by jougs** [comment]
Well spotted. :+1: for merging.

**Comment by jougs** [comment]
Do we need to extend the test to also check larger matrices to prevent a re-occurence of this problem? Moreover, I assume that this might also cause trouble in other locations.

**Comment by heplesser** [comment]
:+1: I had a quick look for `is` and `is not` in `hl_api.py` and did not spot any other problematic uses.
I think @jougs suggestion to add a test with larger matrices is a good one, but I could not see right away which test covers parameter arrays. But this PR can be merged in any case.

**Comment by hannahbos** [comment]
Thanks @jougs @heplesser  for the review. I updated the tests to check larger input arrays.

**Comment by jougs** [comment]
As we don't know a better name, I'm happy to merge this as is.

**Comment by heplesser** [comment]
:+1:

**Pull request merged**
