### PR TITLE
Add standard and detailed timers for benchmarking purposes for NEST 2.20.2

### PR DESCRIPTION
**Pull request by jarsi**
This PR adds timer functionality to NEST 2.20.2. The usage and functionality is similar to what is implemented in PR #1778 and #2063 and addresses the issues raised in #1471.

These timers are implemented:
* `time_construction_create` (basic timer, always enabled)
* `time_construction_connect` (basic timer, always enabled)
* `time_simulate` (basic timer, always enabled)
    * nested in `time_simulate:`
        * `time_update`
        * `time_gather_spike_data`
            * nested in `time_gather_spike_data:`
                * `time_collocate_spike_data`
                * `time_communicate_spike_data`
                * `time_deliver_spike_data`
* `time_communicate_prepare` (basic timer, always enabled)
    * nested in `time_communicate_prepare:`
        * `time_gather_target_data`
            * nested in `time_gather_target_data:`
                * `time_communicate_target_data`

### CODE REVIEW

**Review by hakonsbm — CHANGES_REQUESTED** [review]
Doing a `grep` of the code, I still find some `GetKernelStatus('time')`/`GetKernelStatus("time")`/`GetKernelStatus()['time']` in documentation and examples. Can you update those as well? Other than that, and my comment below, it looks good.

**Comment by jarsi** [comment]
Good catch, thanks for the review. I addressed the issues that you raised.

**Review by hakonsbm — APPROVED** [review]
Thanks, looks good now.

**Comment by jougs** [comment]
@ackurth: friendly ping!

**Comment by ackurth** [comment]
I ran a larger number of benchmarks, everything looked fined.

**Review by ackurth — APPROVED** [review]

**Pull request merged**
