### PR TITLE
Spin_detector precision and documentation fix

### PR DESCRIPTION
**Pull request by SepehrMN**
Fix for the first issue of #698. Precision was already there for some current or future use so I made it compatible with #446. 

I'll fix the documentation of the spin_detector in a separate pull request. It got me thinking, maybe it could be made compatible with more than two states; a model I'm working on can have 4 states.

### CODE REVIEW

**Comment by SepehrMN** [comment]
This can now be merged. Should be straightforward.

**Comment by SepehrMN** [comment]
@jougs Many thanks for your comments. I'll address the issues over the weekend.

**Comment by SepehrMN** [comment]
@jougs I have addressed all issues and wrote full documentation for the device as it was copy pasted from another device. This can now be merged.

**Comment by jougs** [comment]
@apeyser: most of the functionality touched here will have to be re-implemented in NESTio. Can I just merge this now and we review it anew when merging the `nestio` branch back to `master`?

**Comment by apeyser** [comment]
@jougs: sounds reasonable.

**Comment by jougs** [comment]
@apeyser: thanks. Merging.

**Pull request merged**
