### PR TITLE
Properly handle OpenMP linker flags

### PR DESCRIPTION
**Pull request by heplesser**
Until now, we placed `OpenMP_CXX_FLAGS` in the `MODULE_LINK_LIBS` for nest. This is not quite correct and meant that `libomp` was missing from the list of libraries returned by `nest-config --libs`, which in turn caused trouble for building external models with OpenMP, at least on macOS. This PR fixes this.

### CODE REVIEW

**Review by gtrensch — CHANGES_REQUESTED** [review]
Thank you for this contribution. It looks good to me. I would just like to make one suggestion for improvement. In order to report on the OpenMP libraries used, we could add the following to `ConfigureSummary.cmake`, after line 102:
`message( "    Libraries       : ${OpenMP_CXX_LIBRARIES}" )`

**Comment by heplesser** [comment]
> Thank you for this contribution. It looks good to me. I would just like to make one suggestion for improvement. In order to report on the OpenMP libraries used, we could add the following to `ConfigureSummary.cmake`, after line 102: `message( " Libraries : ${OpenMP_CXX_LIBRARIES}" )`

@gtrensch Thanks for the suggestion, fixed!

**Comment by heplesser** [comment]
@gtrensch @clinssen Could you (re-)review asap, this is blocking progress elsewhere.

**Review by pnbabu — APPROVED** [review]

**Review by gtrensch — APPROVED** [review]
Looks good to me!

**Pull request merged**
