### PR TITLE
Fixed SetDefaults for synapse models

### LINKED ISSUE #545: SetDefaults on connections with wrong DataType crashes Nest
In the [master branch](https://github.com/nest/nest-simulator/commit/1fd378f8d95d64ed0af32fadd373a9500a68e719) calling ``SetDefaults`` on a connection with a wrong datatype causes Nest to ``terminate called without an active exception``.  In Nest 2.10 this correctly raised a NestError. Importantly, for neuron models this still works correctly, see below. 

Missing we be missing something in our unittests?
I am unsure whether this is connected to #249, since this actually causes a crash not a silent fail.

Test Bash Script
```bash
echo "Try setting neuron C_m with float"
nest -c "/iaf_neuron << /C_m 10. >> SetDefaults"

echo "------"
echo "Try setting synapse tau_plus with float"
nest -c "/stdp_synapse << /tau_plus 10. >> SetDefaults"

echo "------"
echo "Try setting neuron C_m with int (should fail)"
nest -c "/iaf_neuron << /C_m 10 >> SetDefaults"

echo "------"
echo "Try setting synapse tau_plus with int (should fail)"
nest -c "/stdp_synapse << /tau_plus 10 >> SetDefaults"
```

In [Nest 2.10](https://github.com/nest/nest-simulator/releases) this behaves as expected
```bash
Try setting neuron C_m with float
------
Try setting synapse tau_plus with float
------
Try setting neuron C_m with int (should fail)

Nov 11 16:13:39 SetDefaults_l_D [Error]: TypeMismatch
    Expected datatype: doubletype
    Provided datatype: integertype
------
Try setting synapse tau_plus with int (should fail)

Nov 11 16:13:39 SetDefaults_l_D [Error]: TypeMismatch
    Expected datatype: doubletype
    Provided datatype: integertype
```

In the [master branch](https://github.com/nest/nest-simulator/commit/1fd378f8d95d64ed0af32fadd373a9500a68e719) the last command crashes Nest
```bash
Try setting neuron C_m with float
------
Try setting synapse tau_plus with float
------
Try setting neuron C_m with int (should fail)

Nov 11 16:23:52 SetDefaults_l_D [Error]: TypeMismatch
    Expected datatype: doubletype
    Provided datatype: integertype
------
Try setting synapse tau_plus with int (should fail)

terminate called without an active exception
test.sli: line 14: 41387 Abort trap: 6           nest -c "/stdp_synapse << /tau_plus 10 >> SetDefaults"
```

### PR DESCRIPTION
**Pull request by janhahne**
This PR fixes #545.

### CODE REVIEW

**Comment by janhahne** [comment]
@heplesser Added a regression test, please have another look.

**Comment by heplesser** [comment]
@janhahne Looks good (and even crashes with my version of NEST), but since this is a threading-issue, it would be even better to have a multithreaded part as well. Could you add something like the following at the end of the test?

```
is_threaded not { exit_test_gracefully } if

{
  ResetKernel
  0 << /local_num_threads 4 >> SetStatus
  // bad SetDefaults
} fail_or_die
```

and may be passing one as well?

**Comment by janhahne** [comment]
@heplesser I added the same tests executed with multiple threads.

**Comment by heplesser** [comment]
@flinz Could you check if this solves #545 for you?

**Pull request merged**
