### PR TITLE
Added package attrs to environment.yml

### PR DESCRIPTION
**Pull request by mickelindahl**
When installing using conda I ran in to the problem that package pytest-mypy complained that package attr (part of attrs) was missing when running python -m pytest command during make-installcheck. So have added that package to environment.yml

Have attached my installation file and reduced environment.yml used
[nest-install.zip](https://github.com/nest/nest-simulator/files/12299809/nest-install.zip)

### CODE REVIEW

**Review by gtrensch — APPROVED** [review]
Looks good to me!

**Comment by jessica-mitchell** [comment]
@mickelindahl Could you please fill out the [NEST contributor agreement ](https://nest-simulator.readthedocs.io/en/latest/_downloads/9b65adbdacba6bfed66e68c62af4e308/NEST_Contributor_Agreement.pdf) and email it to info@nest-initiative.org. Thanks!

@terhorstd @heplesser

**Review by jougs — APPROVED** [review]
Fine by me.

**Comment by jessica-mitchell** [comment]
CA acquired, thanks for the PR!

**Pull request merged**
