### PR TITLE
Fix nest-server not starting with apt-installed uwsgi

### LINKED ISSUE #1872: nest-server fails to start when using uwsgi installed via apt
**Describe the bug**
When using `uwsgi` installed via `apt` and not `pip`, running `nest-server start -o` fails with the message

    NEST Server
    -----------
    uwsgi: unrecognized option '--module'
    getopt_long() error

**To Reproduce**

1. Install Nest normally

2. If uwsgi has already been installed via pip, run

        sudo pip3 uninstall uwsgi

2. Install uwsgi via apt

        sudo apt install uwsgi uwsgi-plugin-python3

3. Run ´nest-server start -o´

4. Startup should fail with the error message above

5. The command works when changing the 3 `uwsgi` start commands `extras/nest-server` by adding `--plugin python3`:

       uwsgi --plugin python3 --module nest.server:app ...

**Expected behavior**
nest-server should start regardless of how uwsgi was installed

**Desktop/Environment (please complete the following information):**
 - OS: Ubuntu 20
 - Shell: `bash`
 - Python-Version: Python 3.8
 - NEST-Version: master branch (2869b6364ccd85edf69246deb12c03c05e4a3b49)
 - Installation: Manual

--------------------------------------------------------------------------------
NEST Configuration Summary
--------------------------------------------------------------------------------

Build type          : 
Target System       : Linux
Cross Compiling     : FALSE
C compiler          : GNU 9.3.0 (/usr/bin/cc)
C compiler flags    :  -O2 -Wall -fopenmp -fdiagnostics-color=auto
C++ compiler        : GNU 10.2.0 (/usr/bin/g++-10)
C++ compiler flags  :  -std=c++11 -O2 -Wall -fopenmp -fdiagnostics-color=auto
Build dynamic       : ON

Built-in modules    : models
User modules        : None
Python bindings     : Yes (Python 3.8.5: /usr/bin/python3)
       Includes     : /usr/include/python3.8
       Libraries    : /usr/lib/x86_64-linux-gnu/libpython3.8.so

Cython bindings     : Yes (Cython 0.29.14: /usr/bin/cython3)
MPI4PY header	    : NO 
Use threading       : Yes (OpenMP: -fopenmp)
Use GSL             : Yes (GSL 2.5)
    Includes        : /usr/include
    Libraries       : /usr/lib/x86_64-linux-gnu/libgsl.so;/usr/lib/x86_64-linux-gnu/libgslcblas.so

Use Readline        : No
Use libltdl         : Yes (LTDL 2.4.6)
    Includes        : /usr/include
    Libraries       : /usr/lib/x86_64-linux-gnu/libltdl.so

Use doxygen         : Yes (/usr/bin/doxygen)
                    : target `doc` available
Use MPI             : No
Use MUSIC           : No
Use libneurosim     : No
Use Boost           : Yes (Boost 1.71.0)
    Includes        : /usr/include
    Libraries       : 

Use recording backend Arbor   : No
Use SIONlib         : No

--------------------------------------------------------------------------------

The NEST executable will be installed to:
  /usr/local/bin/

NEST dynamic libraries and user modules will be installed to:
  /usr/local/lib/nest/

Documentation and examples will be installed to:
  /usr/local/share/doc/nest/

PyNEST will be installed to:
    /usr/local/lib/python3.8/site-packages

To set necessary environment variables, add the following line
to your ~/.bashrc :
  source /usr/local/bin/nest_vars.sh

--------------------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by hakonsbm**
This PR replaces #1873. Fixes #1872.

### CODE REVIEW

**Review by babsey — APPROVED** [review]
LGTM.

**Review by steffengraber — COMMENTED** [review]
@hakonsbm I've created a conda env with `conda env create --file conda-nest-simulator-dev.yml`  in `.../extras`
 
Then I intalled uswgi with `conda install -c conda-forge uwsgi` an received the following after `nest-server start`:

```
open("./python3_plugin.so"): No such file or directory [core/utils.c line 3732]
!!! UNABLE to load uWSGI plugin: ./python3_plugin.so: cannot open shared object file: No such file or directory !!!
NEST Server is serving at http://127.0.0.1:5000.
Press any key to stop...
```

Then I deactivated the env and installed uswgi with` sudo apt install uwsgi-plugin-python3`.
Same warning.

(Sure I have built nest and made it run)

**Comment by hakonsbm** [comment]
Adding the `python3` plugin to make the nest-server work with apt-installed uWSGI makes it not work with a pip- or conda-installed uWSGI. That is because the distro-supplied uWSGI is installed in a modular way, requiring a plugin to work with Python, while the pip-/conda-installed uWSGI has Python support built-in, and therefore does not come with any plugins. 

I have instead converted the plugin specification to an argument for nest-server. When uWSGI is installed with apt, you'll have to specify a plugin when you start the nest-server: 
```
> nest-server start -P python3
```

**Comment by babsey** [comment]
LGTM.

**Comment by hakonsbm** [comment]
@steffengraber Ping!

**Review by steffengraber — COMMENTED** [review]
@hakonsbm sorry for the late reply.
Tested and running. Great.
Maybe some documentation explaining the` [-P <PLUGIN>] ` would be nice.
https://nest-simulator.readthedocs.io/en/latest/nest_server.html#install-and-run-nest-server

**Review by steffengraber — APPROVED** [review]
Documentation may also be created in another PR.Documentation may also be created in another PR.

**Review by steffengraber — APPROVED** [review]
Thanks!

**Pull request merged**
