### PR TITLE
Remove undocumented recordables.

### PR DESCRIPTION
**Pull request by heplesser**
This PR provides the last step requested in the code review for #160, thus fixing #77 entirely.

### CODE REVIEW

**Comment by jougs** [comment]
Very nice, so :+1:

**Comment by heplesser** [comment]
Provided that the tests pass, this PR can be merged without review, it is just implementing the final request from the review of #160, which could not be handled in that PR due to organizational issues.

**Comment by abigailm** [comment]
I am hovering with my finger over the merge button... :D

**Comment by abigailm** [comment]
:+1:  and merging

**Pull request merged**
