### PR TITLE
Move CI documentation file to new userdoc directory

### PR DESCRIPTION
**Pull request by clinssen**
Moves the last remaining file in ``doc/contribute`` to ``doc/userdoc/contribute``, thereby eliminating the ``doc/contribute`` directory.

I believe all the links on ReadTheDocs should work OK after this merge. (But I will double-check.)

### CODE REVIEW

**Comment by heplesser** [comment]
Is this file linked from somewhere?

**Comment by clinssen** [comment]
Yes, it's linked from two locations:

```
doc/userdoc/contribute/index.rst:An explanation of our continuous integration pipeline can be found under :doc:`ci`.
doc/userdoc/installation/cmake_options.rst:We :doc:`systematically test <../contribute/ci>` NEST using the GNU gcc and the Clang compiler suites.
```

**Review by jessica-mitchell — APPROVED** [review]
LGTM thanks @clinssen

**Comment by jougs** [comment]
Merging with single approval, as this only concerns documentation and fixes a real problem. Thanks!

**Pull request merged**
