### PR TITLE
Update globals to support execution of hpc_benchmark.py example

### PR DESCRIPTION
**Pull request by jougs**
The title has it all.

### CODE REVIEW

**Comment by jougs** [comment]
@steffengraber: Can you please review this one quickly and recreate the Docker image once this one is merged? Thanks!

**Review by babsey — APPROVED** [review]
LGTM. No problem with testing in examples.

**Comment by jougs** [comment]
As the changes are minimal and @steffengraber is unavailable at the moment, I'm just merging without second review.

**Comment by steffengraber** [comment]
@jougs I was not available the past few days.  The Docker image is rebuilt daily, so everything should be ok.

**Pull request merged**
