### PR TITLE
Add conversion from `IntegerDatum` to `ConstantParameter` in `create_parameter()`

### LINKED ISSUE #2399: Parameter in ConnectLayers doesn't accept integer.
**Describe the bug**
With network of spatial neurons, it shows an error in `nest.Connect` call when the function has spatial distribution, e.g. for `p` and any synaptic specification is an integer: 
```
NESTErrors.BadProperty: BadProperty in SLI function ConnectLayers_g_g_D: Parameter must be parametertype, constant or dictionary.
```

**To Reproduce**
```
import nest
nest.ResetKernel()

positions = nest.spatial.free(nest.random.uniform(-0.5, 0.5), num_dimensions=2)
n1 = nest.Create("iaf_psc_alpha", positions=positions)

nest.Connect(n1, n1,
    conn_spec={"rule": "pairwise_bernoulli", "p": nest.spatial.distance},
    syn_spec={"weight": 1},
)
```
But it works when synaptic weight is float.

**Expected behavior**
As other parameters it should accept integers.

### PR DESCRIPTION
**Pull request by hakonsbm**
Fixes #2399.

### CODE REVIEW

**Comment by babsey** [comment]
Friendly ping. Any updates on this? :flushed:

**Comment by terhorstd** [comment]
@babsey, do you have time to check if this solves the linked issue for you? I added you as a first reviewer, but we need to find a second one before this can go in.

**Review by nicolossus — CHANGES_REQUESTED** [review]
Looks fine in general but check [`ConstantParameter` constructor](https://github.com/nest/nest-simulator/blob/724355258ea4ce81b2e5da3f913dee7a2d6e9598/nestkernel/parameter.h#L136) for consistency with [construction from dictionary](https://github.com/nest/nest-simulator/blob/724355258ea4ce81b2e5da3f913dee7a2d6e9598/nestkernel/parameter.h#L148) w.r.t. `returns_int_only_`.

**Review by nicolossus — APPROVED** [review]
Thanks, looks good to me!

**Review by babsey — APPROVED** [review]
It works. The linked issue was fixed. 

LGTM!

**Pull request merged**
