### PR TITLE
Better documentation of hh_cond_exp_traub and Brette-2007-compatible refractory time

### PR DESCRIPTION
**Pull request by heplesser**
When fixing #473 to make t_ref configurable in hh_cond_exp_traub, we configured the model with `t_ref==0` as default. This does not work properly, since the spike detection mechanism relies on an absolute refractory peroid. This PR sets the default `t_ref=2`ms as used in the Brette et al (2007) review and documents the relation of this model to the review more clearly, as well as differences from the Traub&Miles (1991) model.

See https://github.com/nest/nest-simulator/issues/329#issuecomment-385411618 for a thorough discussion.

### CODE REVIEW

**Comment by heplesser** [comment]
@Silmathoron This neuron model is used for the "hh_coba" benchmark in the Brette et al (2007) simulator review, so we ought to keep it in NEST. Unfortunately, the paper text does not describe spike or reset mechanisms at all. Benchmark code for different simulators [is available on ModelDB](https://senselab.med.yale.edu/ModelDB/ShowModel.cshtml?model=83319&file=/destexhe_benchmarks/#tabs-2), although it is not easy to infer how spike detection is done by the different simulators. The most transparent is Brian:
```Python
P=NeuronGroup(4000,model=eqs,
              threshold=EmpiricalThreshold(threshold=-20*mV,refractory=3*ms),
              implicit=True,freeze=True,compile=False)
```
I.e., a fixed threshold at -20 mV and an absolute refractory period of 3 ms. Since no reset is specified, I assume that without the refractory period, Brian would emit spikes for each time step until membrane potential drops below -20 mV.

I have not been able to find threshold conditions for other simulators, although for Neuron this piece of code
```
proc connect2target() { //$o1 target point process, $o2 returned NetCon
  soma $o2 = new NetCon(&v(1), $o1)
  $o2.threshold = -10 //*	
}
```
looks like there may be a spike threshold of 10 mV.

Quite a mess, but maybe compatibility with the Brian implementation would not be a bad idea?

**Comment by heplesser** [comment]
See also #329.

**Comment by heplesser** [comment]
@Silmathoron @diesmann I have updated the PR after discussions, so default t_ref now is 2 ms. I also made the connection to Brette et al (2007) clearer in the documentation. Could you take a look?

**Comment by Silmathoron** [comment]
@heplesser so all the changes mentioned in #329 including the change in spike detection would be for NEST 3?

**Comment by heplesser** [comment]
@Silmathoron Yes, they would all be for NEST 3 and then in a new model, while the current `hh_cond_exp_traub` would be kept primarily to keep the Brette et al (2007) examples runnning.

**Pull request merged**
