### PR TITLE
Fix invalid paths for cross-references in documentation

### PR DESCRIPTION
**Pull request by JanVogelsang**
There were two wrong paths that I hereby fixed:  
1. In the documentation on the developer workflow page, where there is a link to "Creating a pull request" that is not working.
2. In the regression test 1034.

### CODE REVIEW

**Review by jessica-mitchell — COMMENTED** [review]
@JanVogelsang The reference to the label pull_request works for me.

What is the issue you are having?

**Comment by JanVogelsang** [comment]
[development_workflow.html#pull-request](https://nest-simulator.readthedocs.io/en/stable/contribute/development_workflow.html#pull-request)
This one is broken

**Comment by jougs** [comment]
Ping!

**Comment by JanVogelsang** [comment]
@jessica-mitchell  This PR can actually be deleted now, right?

**Comment by jessica-mitchell** [comment]
@JanVogelsang I'm going to close this as this should get resolved in #2453

**Pull request closed without merging**
