### PR TITLE
Format: limit column width to 80

### PR DESCRIPTION
**Pull request by tammoippen**
This is purely a reformatting of code as requested in #62.

### CODE REVIEW

**Comment by heplesser** [comment]
:+1: from  my side. @apeyser Would you take a look as well?

**Comment by apeyser** [comment]
:+1:

**Comment by Silmathoron** [comment]
Sorry to reopen a merged PR, but fixing the conflicts with mine, I realized that there are still some lines longer 80, for instance in [modelsmodule.cpp](https://github.com/nest/nest-simulator/blob/master/models/modelsmodule.cpp).

**Comment by heplesser** [comment]
@Silmathoron Can you pull the current master into your branch and then use clang-format-3.6 to reformat your code where necessary?

**Comment by Silmathoron** [comment]
Yes I can, but I'm not sure we are talking about the same thing: I was saying that files on the ``nest/master`` branch still have lines longer than 80 (see previous link).

**Comment by heplesser** [comment]
@tammoippen Could you clarify how to proceed here?

**Comment by tammoippen** [comment]
@heplesser @Silmathoron 
`clang-format` makes an estimate on what is best: sticking to 80 column lines and readability (I guess at least), and it also has some problems with breaking some lines, e.g. it tries to break comments by whitespace, hence it has some problems with comments like:

    //-------------------------------------------------------------------------------------

So, the code is at most 80 columns for most lines, with some exceptions. Also see [here](http://llvm.org/releases/3.6.0/tools/clang/docs/ClangFormatStyleOptions.html) for **PenaltyExcessCharacter**.

**Pull request merged**
