### PR TITLE
Rename `calibrate` method to `pre_run_hook`

### LINKED ISSUE #2060: Refactor ``Node::calibrate()`` method
The ``calibrate()`` method should be renamed to something more descriptive, such as ``recompute_internal_variables()``.

It should be removed from the ``Node`` base class and no longer be called from ``NodeManager::prepare_node()``. Instead, it should be a private method, that individual ``Node`` classes call internally from three places: their constructor, their copy constructor, and ``SetStatus()``.

### PR DESCRIPTION
**Pull request by pnbabu**
Fixes #2060 

The `calibrate()` method recomputes the internal variables and is called for every call of simulation. It is now renamed to`pre_run_hook()` which is more descriptive.

### CODE REVIEW

**Review by jougs — COMMENTED** [review]
Looks mostly good to me minus the changes in the cm_* models, where some of the functions should probably be left with the name `calibrate()`, as they are actually calibrating some currents based on some other quantity.

@WillemWybo could you please comment on the changes in those models and say which should be kept with the old name?

**Comment by WillemWybo** [comment]
> Looks mostly good to me minus the changes in the cm_* models, where some of the functions should probably be left with the name `calibrate()`, as they are actually calibrating some currents based on some other quantity.
> 
> @WillemWybo could you please comment on the changes in those models and say which should be kept with the old name?

The calibrate functions mostly compute some quantities based on the simulation time step, so the `pre_run_hook` name seems fine to me. The calibrate function in `cm_default` also sets the all the needed pointers between model variables. Also seems reasonable to me that this would fall under the `pre_run_hook` name.

**Review by jougs — APPROVED** [review]
Thanks for your assessment, @WillemWybo. I thus concur and approve.

**Review by clinssen — APPROVED** [review]
Thank you! Please make concomitant changes in the nest-extension-module repository.

This is tricky to support in NESTML due to #2116, but we should probably deal with that elsewhere.

**Pull request merged**
