### PR TITLE
Handle single node in PlotLayer

### PR DESCRIPTION
**Pull request by ackurth**
Currently, the following code plotting a single node with spatial metadata with internal plotting routines, fails with a Python level ```TypeError```:
```
import nest
import matplotlib.pyplot as plt

num_neurons = 1
extent = 2

neuron = nest.Create(
    'iaf_psc_exp',
    num_neurons,
    positions=nest.spatial.free(
        pos=nest.random.uniform(min=-extent / 2, max=extent / 2),
        num_dimensions=2,
        edge_wrap=True)
)
nest.PlotLayer(neuron)
```
This PR tries to fix this problem.

### CODE REVIEW

**Review by stinebuu — APPROVED** [review]
Thanks!

**Review by hakonsbm — CHANGES_REQUESTED** [review]
Although the single-node case results in a `TypeError`, I think it's more straight-forward to have something like
```python
if (len(layer) == 1):
    pos = GetPosition(layer)
else:
    pos = zip(*GetPosition(layer))
```
or even as a single line
```python
pos = GetPosition(layer) if len(layer) == 1 else zip(*GetPosition(layer))
```

**Comment by ackurth** [comment]
> Although the single-node case results in a `TypeError`, I think it's more straight-forward to have something like
> 
> ```python
> if (len(layer) == 1):
>     pos = GetPosition(layer)
> else:
>     pos = zip(*GetPosition(layer))
> ```
> 
> or even as a single line
> 
> ```python
> pos = GetPosition(layer) if len(layer) == 1 else zip(*GetPosition(layer))
> ```

I changed to code accordingly.

**Review by hakonsbm — APPROVED** [review]
Thanks!

**Pull request merged**
