### PR TITLE
Add sigmoid growth curve for structural plasticity

### PR DESCRIPTION
**Pull request by sanjayankur31**
Butz et al used it in another publication:

[Butz, Markus, Steenbuck, Ines D., and Arjen van Ooyen.
"Homeostatic structural plasticity increases the efficiency of small-world networks." Frontiers in Synaptic Neuroscience 6 (2014): 7.
](http://journal.frontiersin.org/article/10.3389/fnsyn.2014.00007/full)

### CODE REVIEW

**Comment by sanjayankur31** [comment]
@sdiazpier , @heplesser  - would you have the time to review this one? :)

**Comment by sdiazpier** [comment]
Hi dear @sanjayankur31 this is very nice, I wanted to add a sigmoid growth curve for some time now. My first quick look gives me the impression that the code is ok. I only see some issues in the format of the parameter descriptions in the documentation of the growth curve header. Could you please take a look at this? I promise to give it a deep review tomorrow and give you a thumbs up if I see no further issues.

**Comment by sanjayankur31** [comment]
Thanks! I'll fix up the formatting first thing tomorrow morning :)

**Comment by sdiazpier** [comment]
Hi dear @sanjayankur31. I think the code is ok. 
I have a suggestion though. I see that you implemented the sigmoid function just as described in the paper by Dr. Butz. Nevertheless, there is a parameter which I think could be interesting to add to this curve. It is related to the width of the curve (the distance between the curve reaching 95% of the max and 95% of the min. The equation currently looks like this: y = nu ((2 / (1 + e^((Ca(t) - eps)/0.1))) -1 ). I would propose to change it to y = nu ((2 / (1 + e^((Ca(t) - eps) / w ))) -1 ) where w controls the width of the curve. This is useful because the rate of change at the intersection of the curve with the x axis has a lot of influence in the stability of the system. If the rate of change in dz/dt is too high (the width is small) it is more likely that the number of synaptic elements will oscillate more before stability is reached. 
Of course, adding this parameter requires some checks when the creation of the curve is made so that the value is never 0.

**Comment by sanjayankur31** [comment]
Hi @sdiazpier - makes sense. I'll update the code in a few days. Thanks :)

**Comment by sanjayankur31** [comment]
Hi @sdiazpier - I've added the new variable. I've used `w` for the time being, but in `nest_names`, `w` is already defined to mean something else. Should I change it?

I'm also not clear on when one needs to add to `nest_names` and when not. For example, when I'd added the `vogels-sprekeler` synapse model, I hadn't added things like `alpha`, `eta`, or `tau` to `nest_names`. Do I need to ensure that these params and `w` are in `nest_names`? 

Thanks :)

**Comment by sdiazpier** [comment]
Hi dear @sanjayankur31 sorry for the delay. Adding the params to nest_names helps maintainability and consistency when using and extending the code, so the best would be to find another suitable name for the variable w. Maybe it could be changed to psi.
For the vogels-sprekeler model, it would also be good to define the param names in nest_names in case these parameters are specific to your model.

**Comment by heplesser** [comment]
@apeyser Do you think you could take a look at this one?

**Comment by sanjayankur31** [comment]
Working on this now. Will hopefully push new commits before the weekend. :)

**Comment by sdiazpier** [comment]
Dear @sanjayankur31 sorry for the delay to respond. Could you please merge the latest changes in nest_names.h? For the rest the PR looks ready for me. :+1: 
Thanks for adding this nice functionality and for your active work on structural plasticity and nest.

**Comment by sanjayankur31** [comment]
dear @sdiazpier  - I've resolved the conflicts and merged with master. Please do let me know if there's anything else :)

**Comment by sanjayankur31** [comment]
@sdiazpier - updated to remove conflicts.

**Comment by sanjayankur31** [comment]
I've corrected the conflicts. Please let me know if there are any more changes required. Cheers!

**Comment by flinz** [comment]
from me :+1:
thanks for your work!

**Comment by sanjayankur31** [comment]
@flinz - thank you for the review!

**Comment by heplesser** [comment]
@jougs This is ready to merge, I leave it to you whether you want to include it with NEST 2.12.

**Pull request merged**
