### PR TITLE
Fix issue 519: Improved connection parameter skipping with connection rule all_to_all

### PR DESCRIPTION
**Pull request by golosio**
This PR fixes issue 519: https://github.com/nest/nest-simulator/issues/519
in conn_builder.cpp, lines as:

```
  for ( GIDCollection::const_iterator sgid = sources_->begin();
        sgid != sources_->end();
        ++sgid )
    skip_conn_parameter_( tid );
```

have been replaced by passing the number of source neurons as second argument of the call to skip_conn_parameter.
I also wrote an MPI test for connection with array parameters and connection rule all_to_all.

### CODE REVIEW

**Comment by golosio** [comment]
I propose @hannahbos and @heplesser as reviewers.

**Comment by golosio** [comment]
@heplesser why this PR is not going to travis? I do not understand what does it mean this branch has a conflict. Does it mean that there was some modification of conn_builder.cpp that I did not pull before doing my changes?

**Comment by heplesser** [comment]
@golosio Curious that it didn't go to Travis. It may be because the title contained "skip", but I thought one had to add `[skip ci]` to the title to suppress Travis checks.

@lekshmideepu Do you have any idea what is going on?

**Comment by golosio** [comment]
@heplesser Indeed the file conn_builder.cpp has been modified while I was working on it, so there was a conflict. Now I got the last version of the file and I applied the same changes on this file. Everything should be ok now.

**Comment by hannahbos** [comment]
Thanks for improving this. :+1:

**Pull request merged**
