### PR TITLE
Update models with adaptation mechanisms and change tag 'adaptive threshold' to 'adaptation'

### PR DESCRIPTION
**Pull request by jessica-mitchell**
This PR updates the model tag for models that use an adaptation mechanism to 'adaptation' after discussions with @ddahmen 
The reason is that not all the models have the same adaptation mechanism, and the ones labeled with adaptive threshold (i.e. 'aeif' models) technically do not have an adaptive threshold. 
We were also missing tags for several models that have an adaptation mechanism but were not 'aeif' models.

See Read the Docs output here: https://nest-simulator--3241.org.readthedocs.build/en/3241/models/index.html#adaptation

@shimoura agreed to review, thanks!

### CODE REVIEW

**Review by shimoura — CHANGES_REQUESTED** [review]
The ones included seem right. I noted one that is missing. The "Izhikevich" model can present spike frequency adaptation.

**Comment by jessica-mitchell** [comment]
> The ones included seem right. I noted one that is missing. The "Izhikevich" model can present spike frequency adaptation.

I don't see, however, an obvious parameter that reflects an adaptive mechanism in the model code

**Comment by shimoura** [comment]
> > The ones included seem right. I noted one that is missing. The "Izhikevich" model can present spike frequency adaptation.
> 
> @shimoura I don't see, however, an obvious parameter that reflects an adaptive mechanism in the model code

The model is similar to aeif category. The main difference is the dependence of membrane voltage with quadratic terms instead of exponential. And the parameters "a", "b", and "d" are in some way similar to the parameters "a" and "b" of aeif models. 
In summary, different values of these parameters will give similar behavior as aeif models. The spike frequency adaptation is one of them. Fig. 2 of the main Izhikevich reference shows it. 

Obs: I noticed in Izhikevich documentation that du/dt should be dU_m/dt to match the variable names.

**Review by shimoura — APPROVED** [review]

**Comment by jessica-mitchell** [comment]
Merging with 1 reviewer, since it's documentation related, also discussed in person at NEST meeting, to general approval of concept

**Pull request merged**
