### PR TITLE
Add CMake flag to enable/disable hpc synapses

### PR DESCRIPTION
**Pull request by jakobj**
under the assumption that most users do not use the hpc versions of the synapses, this PR adds a cmake option to enable/disable(default) hpc synapse models. this allows for more custom models to be registered before running out of possible synapse models. partly addresses #1043 

@heplesser @suku248

### CODE REVIEW

**Comment by ikitayama** [comment]
Could you keep it enable by default? I’m one of those HPC users.

**Comment by jakobj** [comment]
thanks for the comment @ikitayama. i think this is a matter of taste. since most users will not use hpc synapses, and those who do, including you, know how to adjust cmake 
options to their desire, I thought it would be more reasonable to set the default to off, but I am open to discuss this.

**Comment by ikitayama** [comment]
@jakobj - I suppose a new CMake variable would be easily overlooked thus ended up a binary that is built to not load the HPC-themed models. And an HPC user might waist his/her couples of hours wondering at to why the models aren't loaded at run time. This is the scenario I worry about.

Given that we'd let many modules piled up in the code base, I'd like to oppose introducing module
load/unload switch in a ad-hoc fashion.

**Comment by jakobj** [comment]
closing, see #1043

**Pull request closed without merging**
