### PR TITLE
Topology tests into installcheck

### PR DESCRIPTION
**Pull request by hakonsbm**
This PR

- Converts manual tests in topology to MPI and unittests to be used with installcheck.
- Converts all SLI topology connection tests to topology unittests with reference results in each file.
- Changes the installcheck script to include the topology SLI and Python tests.

This addresses parts of #302.

### CODE REVIEW

**Comment by heplesser** [comment]
@jougs Could you mainly check the technical side, i.e., installation and running of tests?
@jhnnsnk Could you mainly look at the tests themselves? They have all been around for a long time, but just as manual tests.

Don't be scared by the seemingly very large number of changed files. This is mostly because files have been moved and reference data that used to be in three data files per test are now included in the actual test files. So most of the file changes are just deletions.

**Comment by heplesser** [comment]
@hakonsbm Could you update this PR to resolve the conflict with master?

**Comment by hakonsbm** [comment]
@heplesser Updated.

**Comment by hakonsbm** [comment]
@jhnnsnk Thank you for your review. I have fixed some of the inconsistencies, but others are not that strictly enforced in the testsuite. Addressing your points

- The purpose of this PR is to make the existing topology tests available with installcheck. But I have created an issue, #772, on creating new tests to cover the functionality mentioned.
- While it is good practice to not leave arguments on the stack, this is not strictly enforced in many tests in the testsuite.
- I have added `ResetKernel` to tests lacking this. Leaving namespace may also be good practice, but is not strictly enforced in the testsuite.
- The change of resolution is removed from tests that do not need it.

**Comment by jhnnsnk** [comment]
Thanks for addressing my points.
:+1:

**Comment by heplesser** [comment]
Release note: Added tests for topology module to testsuite.

**Pull request merged**
