### PR TITLE
Hike and enforce Python version requirement to 3.8

### LINKED ISSUE #1953: Hike Python requirements to Python 3.8
The Open Developer VC on 1 March 2021 decided to raise the minimum Python requirement for NEST to Python 3.8, released Nov 2019.

In solving this issue, all documentation should be checked for mentions of Python version numbers.

I suggest to close #1932 and create a new PR for this issue.

### PR DESCRIPTION
**Pull request by hakonsbm**
The minimum requirement for Python version is raised to 3.8, and enforced at CMake configuration. Additionally, for Cython, a version of 0.28.3 or later is enforced because of a change in the Python C api with Python 3.7.

Finding of Python is refactored from using the deprecated CMake functions `FindPythonInterp` and `FindPythonLibs` to use `FindPython`.

All documentation mentioning minor Python version numbers is updated.

This PR supersedes #1932 and fixes #1953.

### CODE REVIEW

**Comment by heplesser** [comment]
@hakonsbm Works nicely on my Apple Silicon Mac.

**Comment by hakonsbm** [comment]
On Travis CMake seems to not be able to find the Python library and include directories. This can be because of some mismatched paths when setting `-DPYTHON_LIBRARY` and `-DPYTHON_INCLUDE_DIR`, or possibly because it's using a slightly older CMake version (3.12.4). Should I try to fix it, or should we ignore Travis here because the GitHub Actions jobs are passing?

**Comment by heplesser** [comment]
@lekshmideepu @jougs @terhorstd What do you think about the Python problems on Travis? I would tend to ignore them, given that the Python setup on Travis has always been fickle. If one of you sees a straightforward fix for Travis, that would be good, obviously. #1948 also looks relevant here.

**Comment by Helveg** [comment]
Travis is not the only env where the Python libs and include dirs aren't found. Also the 15% of Python users that use `pyenv` have to manually look for their libs and include dirs.

**Comment by hakonsbm** [comment]
It works fine for me with `pyenv`, using CMake 3.16.3. What CMake version and CMake command do you use, @Helveg?

**Comment by Helveg** [comment]
Oh sorry, I got things mixed up, using the new `FindPython3` CMake module works

**Comment by Helveg** [comment]
@hakonsbm CMake version 3.16.3 WSL2 Ubuntu 20, using pyenv Python 3.8.6:

```
cmake ..
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Python (missing: Python_EXECUTABLE Python_INCLUDE_DIRS
  Interpreter Development) (found suitable version "3.8", minimum required is
  "3.8")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPython/Support.cmake:2214 (find_package_handle_standard_args)
  /usr/share/cmake-3.16/Modules/FindPython.cmake:304 (include)
  cmake/ProcessOptions.cmake:401 (find_package)
  CMakeLists.txt:145 (nest_process_with_python)
```

Any idea?

**Comment by hakonsbm** [comment]
Thanks for testing again, @Helveg. I've updated FindCython.cmake and UseCython.cmake files, but I still can't reproduce your errors with `pyenv`, neither with Python 3.9.1 or 3.8.6. It's also strange that they are treated differently by CMake for you.

As you say, `FindPythonLibs` is needed to get the `python_add_module` function. But the variables set by it is not used, so I have removed the `REQUIRED` argument. `FindPythonLibs` is deprecated, however, and I can't find an alternative to `python_add_module`. Maybe we should just copy the 30 lines of the `python_add_module` function from the source so we can remove `FindPythonLibs` completely.

**Comment by Helveg** [comment]
Thanks for going over the cython files; I think vendoring the `python_add_module` code is a good solution. If you're feeling generous and open-sourcey, you could also open a PR on the cmake repo to include it in `FindPython` :)

**Review by gtrensch — APPROVED** [review]
Thank you for this contribution. 👍 I have successfully tested it on Ubuntu.

**Review by clinssen — APPROVED** [review]
I tested this on Debian 10 with CMake 3.20.0 and Python 3.9.

**Pull request merged**
