### PR TITLE
Fix linking problems on OSX in presence of MPI4Py

### LINKED ISSUE #1678: Compilation/linking error: `ld: symbol(s) not found for architecture x86_64`
**Describe the bug**
I'm seeing this error while compiling the current master (at ba76461b140e17d41a7061d2e6831dde36d75539),
which does not appear to be a duplicate of any closed issues I could find:
```
$ make -j4
...
[ 96%] Building CXX object nest/CMakeFiles/nest_lib.dir/neststartup.cpp.o
[ 97%] Building CXX object nest/CMakeFiles/nest_lib.dir/sli_neuron.cpp.o
[ 97%] Linking CXX executable nest
[ 97%] Built target nest
Scanning dependencies of target run_all_cpptests
[ 98%] Building CXX object testsuite/cpptests/CMakeFiles/run_all_cpptests.dir/run_all.cpp.o
[ 98%] Linking CXX shared library libnest.dylib
ld: warning: -pie being ignored. It is only used when linking a main executable
Undefined symbols for architecture x86_64:
  "_PyCapsule_GetName", referenced from:
      __Pyx_ImportFunction(_object*, char const*, void (**)(), char const*) in neststartup.cpp.o
  "_PyCapsule_GetPointer", referenced from:
      __Pyx_ImportFunction(_object*, char const*, void (**)(), char const*) in neststartup.cpp.o
  "_PyCapsule_IsValid", referenced from:
      __Pyx_ImportFunction(_object*, char const*, void (**)(), char const*) in neststartup.cpp.o
  "_PyDict_GetItemString", referenced from:
      __Pyx_ImportFunction(_object*, char const*, void (**)(), char const*) in neststartup.cpp.o
  "_PyErr_Format", referenced from:
      __Pyx_ImportFunction(_object*, char const*, void (**)(), char const*) in neststartup.cpp.o
      __Pyx_ImportType(_object*, char const*, char const*, unsigned long, __Pyx_ImportType_CheckSize) in neststartup.cpp.o
  "_PyErr_WarnEx", referenced from:
      __Pyx_ImportType(_object*, char const*, char const*, unsigned long, __Pyx_ImportType_CheckSize) in neststartup.cpp.o
  "_PyExc_ImportError", referenced from:
      __Pyx_ImportFunction(_object*, char const*, void (**)(), char const*) in neststartup.cpp.o
  "_PyExc_TypeError", referenced from:
      __Pyx_ImportFunction(_object*, char const*, void (**)(), char const*) in neststartup.cpp.o
      __Pyx_ImportType(_object*, char const*, char const*, unsigned long, __Pyx_ImportType_CheckSize) in neststartup.cpp.o
  "_PyExc_ValueError", referenced from:
      __Pyx_ImportType(_object*, char const*, char const*, unsigned long, __Pyx_ImportType_CheckSize) in neststartup.cpp.o
  "_PyImport_ImportModule", referenced from:
      set_communicator(_object*) in neststartup.cpp.o
  "_PyModule_GetName", referenced from:
      __Pyx_ImportFunction(_object*, char const*, void (**)(), char const*) in neststartup.cpp.o
  "_PyOS_snprintf", referenced from:
      __Pyx_ImportType(_object*, char const*, char const*, unsigned long, __Pyx_ImportType_CheckSize) in neststartup.cpp.o
  "_PyObject_GetAttrString", referenced from:
      __Pyx_ImportFunction(_object*, char const*, void (**)(), char const*) in neststartup.cpp.o
      __Pyx_ImportType(_object*, char const*, char const*, unsigned long, __Pyx_ImportType_CheckSize) in neststartup.cpp.o
  "_PyType_IsSubtype", referenced from:
      set_communicator(_object*) in neststartup.cpp.o
  "__Py_Dealloc", referenced from:
      set_communicator(_object*) in neststartup.cpp.o
      __Pyx_ImportFunction(_object*, char const*, void (**)(), char const*) in neststartup.cpp.o
      __Pyx_ImportType(_object*, char const*, char const*, unsigned long, __Pyx_ImportType_CheckSize) in neststartup.cpp.o
ld: symbol(s) not found for architecture x86_64
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [nest/libnest.dylib] Error 1
make[1]: *** [nest/CMakeFiles/nest_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**To Reproduce**
1. Conda env file:
```
name: nest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - openmpi-mpicc
  - openmpi-mpicxx
  - ipython
  - boost
  - libtool
  - readline
  - mpi4py
  - openmp
  - gsl
  - cython
  - doxygen
  - graphviz  # for dot
  - pkg-config
```
2. packages:
```
$ conda list
# packages in environment at /Users/ehagen/anaconda3/envs/nest:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0           py38h32f6830_1001    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
boost                     1.73.0           py38hd74bcbf_0    conda-forge
boost-cpp                 1.73.0               hef959ae_1    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cctools                   927.0.2              h5ba7a2e_4    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
clang                     9.0.1           default_hf57f61e_0    conda-forge
clang-tools               9.0.1           default_hf57f61e_0    conda-forge
clang_osx-64              9.0.1                h05bbb7f_0    conda-forge
clangxx                   9.0.1           default_hf57f61e_0    conda-forge
clangxx_osx-64            9.0.1                h05bbb7f_2    conda-forge
compiler-rt               9.0.1                h6a512c6_3    conda-forge
compiler-rt_osx-64        9.0.1                h99342c6_3    conda-forge
cython                    0.29.20          py38hc84c608_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
doxygen                   1.8.18               h72f44dd_0    conda-forge
freetype                  2.10.2               h8da9a1a_0    conda-forge
graphviz                  2.42.3               h98dfb87_0    conda-forge
gsl                       2.6                  ha2d443c_0    conda-forge
icu                       67.1                 h4a8c4bd_0    conda-forge
ipython                   7.16.1           py38h23f93f0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.1           py38h32f6830_0    conda-forge
jpeg                      9d                   h0b31af3_0    conda-forge
ld64                      450.3                h3c32e8a_4    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcxx                    10.0.0               h1af66ff_2    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm9                  9.0.1                h7475705_1    conda-forge
libopenblas               0.3.7                h3d69b6c_4    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libtool                   2.4.6             h1de35cc_1002    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
llvm-openmp               8.0.1                h770b8ee_0    conda-forge
lz4-c                     1.9.2                h4a8c4bd_1    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.0.3            py38h5dec745_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.18.5           py38h1f821a2_0    conda-forge
openmp                    8.0.1                         0    conda-forge
openmpi                   4.0.4                hed52333_0    conda-forge
openmpi-mpicc             4.0.4                ha1c9252_0    conda-forge
openmpi-mpicxx            4.0.4                h962d5db_0    conda-forge
openssl                   1.1.1g               h0b31af3_0    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pip                       20.1.1                     py_1    conda-forge
pkg-config                0.29.2            hdc84dc8_1006    conda-forge
prompt-toolkit            3.0.5                      py_1    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.6.1                      py_0    conda-forge
python                    3.8.3           cpython_hd5f0129_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                49.1.0           py38h32f6830_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               h93121df_0    conda-forge
tapi                      1000.10.8            ha1b3eb9_4    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
traitlets                 4.3.3            py38h32f6830_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h0b31af3_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                h4b3e974_3    conda-forge
```
3. misc.
```
$ conda info
     active environment : nest
    active env location : /Users/ehagen/anaconda3/envs/nest
            shell level : 1
       user config file : /Users/ehagen/.condarc
 populated config files : /Users/ehagen/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.1
         python version : 3.7.6.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/ehagen/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/ehagen/anaconda3/pkgs
                          /Users/ehagen/.conda/pkgs
       envs directories : /Users/ehagen/anaconda3/envs
                          /Users/ehagen/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 505:20
             netrc file : None
           offline mode : False
```
4. Build script:
```
# create conda env
conda env create -f nest_environment.yml
conda activate nest

# conda environment path
export CONDAENV=$HOME/anaconda3/envs/nest

# compilers
export CC=$CONDAENV/bin/mpicc
export CXX=$CONDAENV/bin/mpicxx

# path variables
    export NESTBLD=$HOME/Repositories/nest-simulator-bld
    export NESTSOURCES=$HOME/Repositories/nest-simulator
    export NESTPREFIX=$CONDAENV

# create build directory
mkdir $NESTBLDs
cd $NESTBLD
rm -r *

# configure NEST
cmake -DCMAKE_INSTALL_PREFIX:PATH=$NESTPREFIX \
      -Dwith-mpi=ON \
      -Dwith-python=ON \
      -DLTDL_ROOT_DIR=$CONDAENV \
      -Dwith-gsl=$CONDAENV \
      -Dwith-openmp=ON \
      -Dwith-readline=$CONDAENV \
      -DCMAKE_C_COMPILER=$CC \
      -DCMAKE_CXX_COMPILER=$CXX \
      $NESTSOURCES
make
```
4. cmake summary
```
Build type          : 
Target System       : Darwin
Cross Compiling     : FALSE
C compiler          : Clang 9.0.1 (/Users/ehagen/anaconda3/envs/nest/bin/mpicc)
C compiler flags    : -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/ehagen/anaconda3/envs/nest/include -O2 -Wall -fopenmp=libomp    
C++ compiler        : Clang 9.0.1 (/Users/ehagen/anaconda3/envs/nest/bin/mpicxx)
C++ compiler flags  : -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -isystem /Users/ehagen/anaconda3/envs/hybridlfpy/include -std=c++11 -O2 -Wall -fopenmp=libomp  
Build dynamic       : ON

Built-in modules    : models;precise;topology
User modules        : None
Python bindings     : Yes (Python 3.8.3: /Users/ehagen/anaconda3/envs/nest/bin/python3)
       Includes     : /Users/ehagen/anaconda3/envs/nest/include/python3.8
       Libraries    : /Users/ehagen/anaconda3/envs/nest/lib/libpython3.8.dylib

Cython bindings     : Yes (Cython 0.29.20: /Users/ehagen/anaconda3/envs/nest/bin/cython)
MPI4PY header	    : Yes (/Users/ehagen/anaconda3/envs/nest/lib/python3.8/site-packages/mpi4py/include)
Use threading       : Yes (OpenMP: -fopenmp=libomp)
Use GSL             : Yes (GSL 2.6)
    Includes        : /Users/ehagen/anaconda3/envs/nest/include
    Libraries       : /Users/ehagen/anaconda3/envs/nest/lib/libgsl.dylib;/Users/ehagen/anaconda3/envs/nest/lib/libgslcblas.dylib

Use Readline        : Yes (GNU Readline 8.0)
    Includes        : /Users/ehagen/anaconda3/envs/nest/include
    Libraries       : /Users/ehagen/anaconda3/envs/nest/lib/libreadline.dylib;/Users/ehagen/anaconda3/envs/nest/lib/libncurses.dylib

Use libltdl         : Yes (LTDL 2.4.6)
    Includes        : /Users/ehagen/anaconda3/envs/nest/include
    Libraries       : /Users/ehagen/anaconda3/envs/nest/lib/libltdl.dylib

Use doxygen         : Yes (/Users/ehagen/anaconda3/envs/nest/bin/doxygen)
                    : target `doc` available
    `dot` available : Yes (/Users/ehagen/anaconda3/envs/nest/bin/dot)
                    : target `fulldoc` available
Use MPI             : Yes (MPI: /Users/ehagen/anaconda3/envs/nest/bin/mpicxx)
    FLAGS           : 
    Includes        : 
    Link Flags      : 
    Libraries       : 

Use MUSIC           : No
Use libneurosim     : No
Use Boost           : Yes (Boost 1.73.0)
    Includes        : /Users/ehagen/anaconda3/envs/nest/include
    Libraries       : 

Use recording backend Arbor   : No
Use SIONlib         : No
```

**Expected behavior**
A successful build. 

**Desktop/Environment (please complete the following information):**
 - OS: macOS 10.14.6
 - Python-Version: 3.8
 - NEST-Version: ba76461b140e17d41a7061d2e6831dde36d75539
 - Installation: See above

### PR DESCRIPTION
**Pull request by heplesser**
This should fix #1678.

### CODE REVIEW

**Comment by heplesser** [comment]
@espenhgn Could you check if this solves the problem for you as well? I have not yet tested if NEST with mpi4py then works properly, only that `import nest` works.

**Comment by espenhgn** [comment]
Thanks @heplesser. I got one failing python test with the macports build (but that seems about normal):
```
======================================================================
FAIL: testWithMPI (nest.tests.test_connect_all_patterns.TestConnectAllPatterns)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ehagen/.local/nest_py38/lib/python3.8/site-packages/nest/tests/test_connect_all_patterns.py", line 58, in testWithMPI
    self.assertTrue(not failing_tests, 'The following tests failed when ' +
AssertionError: False is not true : The following tests failed when executing with "mpirun -np 2 nosetests [script]": test_connect_all_to_all.py, test_connect_one_to_one.py, test_connect_fixed_indegree.py, test_connect_fixed_outdegree.py, test_connect_fixed_total_number.py, test_connect_pairwise_bernoulli.py

----------------------------------------------------------------------
Ran 357 tests in 58.436s

FAILED (failures=1, skipped=7)
```
Will try the conda build next.

**Comment by espenhgn** [comment]
The conda build will compile fine as well, but the same test as above fails. Not sure if that is a concern or not. In both cases I configured the build with most options enabled:
```
cmake -DCMAKE_INSTALL_PREFIX:PATH=$NESTPREFIX \
      -Dwith-mpi=ON \
      -Dwith-python=ON \
      -Dwith-ltdl=ON \
      -Dwith-gsl=ON \
      -Dwith-openmp=ON \
      -Dwith-readline=ON \
      -Dwith-boost=ON \
      -DMPI_C_COMPILER=$MPICC \
      -DMPI_CXX_COMPILER=$MPICXX \
      -DCMAKE_C_COMPILER=$CC \
      -DCMAKE_CXX_COMPILER=$CXX \
      $NESTSOURCES
```
If the failing test is a non-concern, I'm fine with merging.

**Comment by heplesser** [comment]
@espenhgn All tests must pass before merging, and certainly the connect all patterns test. For a reason I have not fully checked  yet, the Python tests did not run on my machine last night, so I didn't catch this one. And the OSX test on Travis builds without MPI, which probably explains why all worked on Travis. I will explore.

**Comment by hakonsbm** [comment]
@heplesser It doesn't look like Travis installs mpi4py, or at least it cannot find it. So the connect all patterns test is never run on Travis. And it also currently fails on my machine with master.

**Comment by espenhgn** [comment]
It looks like TestConnectAllPatterns doesn't capture the output correct when running the scripts 
```
scripts = ["test_connect_all_to_all.py",
                   "test_connect_one_to_one.py",
                   "test_connect_fixed_indegree.py",
                   "test_connect_fixed_outdegree.py",
                   "test_connect_fixed_total_number.py",
                   "test_connect_pairwise_bernoulli.py"
                   ]
```
with MPI, where `process.returncode returns 1`. I can run all of them manually from the command line without issues as `mpirun -np 2 nosetests <script>` 

It's weird that stdout and stderr output are empty byte strings while retcode is 1:
```
            ....
            process = sp.Popen(command, stdout=sp.PIPE, stderr=sp.PIPE)
            stdout, stderr = process.communicate()
            retcode = process.returncode
            print(command, stdout, stderr, retcode)
```
results in
```
['mpirun', '-np', '2', 'nosetests', '/Users/ehagen/anaconda3/envs/nest/lib/python3.8/site-packages/nest/tests/test_connect_all_to_all.py'] b'' b'' 1
['mpirun', '-np', '2', 'nosetests', '/Users/ehagen/anaconda3/envs/nest/lib/python3.8/site-packages/nest/tests/test_connect_one_to_one.py'] b'' b'' 1
['mpirun', '-np', '2', 'nosetests', '/Users/ehagen/anaconda3/envs/nest/lib/python3.8/site-packages/nest/tests/test_connect_fixed_indegree.py'] b'' b'' 1
['mpirun', '-np', '2', 'nosetests', '/Users/ehagen/anaconda3/envs/nest/lib/python3.8/site-packages/nest/tests/test_connect_fixed_outdegree.py'] b'' b'' 1
['mpirun', '-np', '2', 'nosetests', '/Users/ehagen/anaconda3/envs/nest/lib/python3.8/site-packages/nest/tests/test_connect_fixed_total_number.py'] b'' b'' 1
['mpirun', '-np', '2', 'nosetests', '/Users/ehagen/anaconda3/envs/nest/lib/python3.8/site-packages/nest/tests/test_connect_pairwise_bernoulli.py'] b'' b'' 1
``` 
 so no error message appears to be captured

**Comment by espenhgn** [comment]
> @heplesser It doesn't look like Travis installs mpi4py, or at least it cannot find it. So the connect all patterns test is never run on Travis. And it also currently fails on my machine with master.

I think it used to be the case that mpi4py must be pip installed. At least that's what I did for the LFPy travis.yml file. https://github.com/LFPy/LFPy/blob/master/.travis.yml

**Comment by espenhgn** [comment]
Hi again. The test function defined in `test_connect_all_patterns.py` is broken. Some interactive testing with one of the scripts without and with import of MPI yields
```
In [1]: import subprocess as sp                                                                                                                                                          

In [2]: command = "mpirun -np 2 nosetests /Users/ehagen/anaconda3/envs/nest/lib/python3.8/site-packages/nest/tests/test_connect_all_to_all.py"                                           

In [3]: process = sp.Popen(command.split(), stdout=sp.PIPE, stderr=sp.PIPE)                                                                                                              

In [4]: stdout, stderr = process.communicate()                                                                                                                                           

In [5]: process.returncode                                                                                                                                                               
Out[5]: 0

In [6]: print(stdout)                                                                                                                                                                    
b"\n              -- N E S T --\n  Copyright (C) 2004 The NEST Initiative\n\n Version: fix-1678-broken-build@74dfd2cb6\n Built: Aug  6 2020 09:27:47\n\n This program is provided AS IS and comes with\n NO WARRANTY. See the file LICENSE for details.\n\n Problems or suggestions?\n   Visit https://www.nest-simulator.org\n\n Type 'nest.help()' to find out more about NEST.\n\n\n              -- N E S T --\n  Copyright (C) 2004 The NEST Initiative\n\n Version: fix-1678-broken-build@74dfd2cb6\n Built: Aug  6 2020 09:27:47\n\n This program is provided AS IS and comes with\n NO WARRANTY. See the file LICENSE for details.\n\n Problems or suggestions?\n   Visit https://www.nest-simulator.org\n\n Type 'nest.help()' to find out more about NEST.\n\n"

In [7]: print(stderr)                                                                                                                                                                    
b'........................................................................................\n----------------------------------------------------------------------\nRan 44 tests in 1.207s\n\nOK\n\n----------------------------------------------------------------------\nRan 44 tests in 1.207s\n\nOK\n'
```
vs. 
```
In [1]: import subprocess as sp                                                                                                                                                          

In [2]: from mpi4py import MPI                                                                                                                                                           

In [3]: command = "mpirun -np 2 nosetests /Users/ehagen/anaconda3/envs/nest/lib/python3.8/site-packages/nest/tests/test_connect_all_to_all.py"                                           

In [4]: process = sp.Popen(command.split(), stdout=sp.PIPE, stderr=sp.PIPE)                                                                                                              

In [5]: process = sp.Popen(command.split(), stdout=sp.PIPE, stderr=sp.PIPE)                                                                                                              

In [6]: stdout, stderr = process.communicate()                                                                                                                                           

In [7]: process.returncode                                                                                                                                                               
Out[7]: 1

In [8]: print(stdout)                                                                                                                                                                    
b''

In [9]: print(stderr)                                                                                                                                                                    
b''
```

Is this not just related to Python's global interpreter lock (GIL)?

**Comment by heplesser** [comment]
@espenhgn @hakonsbm Thank you for the detective work! In a way good to know that the problem test fails on Linux as well, but unfortunate that we did not notice that it was skipped in all our Travis tests. Can one of you create a separate issue with critical priority for (a) ensuring the test is run at least in the full Linux build on Travis and (b) that it passes? Then we can focus here on the linking issue under OSX.

**Comment by espenhgn** [comment]
Ok, I can create a ticket describing the issue.

**Comment by espenhgn** [comment]
@heplesser; I fixed the failing test in PR #1720.

**Comment by espenhgn** [comment]
#1720 has been merged, fixing the failing `test_connect_all_patterns.py`.

**Comment by heplesser** [comment]
@espenhgn Does this fix work for you?

**Comment by espenhgn** [comment]
> @espenhgn Does this fix work for you?

Hi @heplesser , the fix worked prevously, but I haven't tried recompiling this PR merging upstream changes yet (including #1720 which was merged). Can do so later today (but I don't expect any problems).

**Comment by espenhgn** [comment]
I tested merging this PR with master and it looks good to go. 
The Python test suite now completes without problems:
```
$ python -c "import nest; nest.test()"
...
Ran 357 tests in 61.615s

OK (skipped=7)
```

`make installcheck` produces quite a few errors with MPI as my macbook doesn't have 4 MPI slots, so I think those failing tests are a non issue:
```
----------------------------------------------------------------------
NEST Testsuite Results
----------------------------------------------------------------------
Phase                    Tests   Skipped  Failures    Errors      Time
----------------------------------------------------------------------
01 basetests                 6         0         0         0       8.0
02 selftests                 8         4         0         0      18.0
03 unittests               186         1         0         0      75.0
04 regressiontests          93         6         0         0      50.0
05 mpitests                 77         0        59         0      44.0
07 pynesttests             755         8         0         0      95.6
08 cpptests                 29         0         0         0       0.0
----------------------------------------------------------------------
Total                     1154        19        59         0     290.6
----------------------------------------------------------------------

THE NEST TESTSUITE DISCOVERED PROBLEMS
    The following tests failed
    | mpi_selftests.pass/test_distributed_assert_or_die.sli.mpi_selftests/pass/test_distributed_assert_or_die.sli
    | mpi_selftests.pass/test_distributed_collect_assert_or_die.sli.mpi_selftests/pass/test_distributed_collect_assert_or_die.sli
    | mpi_selftests.pass/test_distributed_invariant_assert_or_die.sli.mpi_selftests/pass/test_distributed_invariant_assert_or_die.sli
    | mpi_selftests.pass/test_distributed_pass_or_die.sli.mpi_selftests/pass/test_distributed_pass_or_die.sli
    | mpi_selftests.pass/test_distributed_process_invariant_collect_assert_or_die.sli.mpi_selftests/pass/test_distributed_process_invariant_collect_assert_or_die.sli
    | mpi_selftests.pass/test_distributed_process_invariant_events_assert_or_die.sli.mpi_selftests/pass/test_distributed_process_invariant_events_assert_or_die.sli
    | mpi_selftests.pass/test_distributed_rank_invariant_collect_assert_or_die.sli.mpi_selftests/pass/test_distributed_rank_invariant_collect_assert_or_die.sli
    | mpitests.issue-281.sli.mpitests/issue-281.sli
    | mpitests.issue-600.sli.mpitests/issue-600.sli
    | mpitests.test_all_to_all.sli.mpitests/test_all_to_all.sli
    | mpitests.test_connect_array_all_to_all_mpi.sli.mpitests/test_connect_array_all_to_all_mpi.sli
    | mpitests.test_connect_array_fixed_indegree_mpi.sli.mpitests/test_connect_array_fixed_indegree_mpi.sli
    | mpitests.test_connect_array_fixed_outdegree_mpi.sli.mpitests/test_connect_array_fixed_outdegree_mpi.sli
    | mpitests.test_delay_exchange.sli.mpitests/test_delay_exchange.sli
    | mpitests.test_fixed_indegree.sli.mpitests/test_fixed_indegree.sli
    | mpitests.test_gamma_sup_generator.sli.mpitests/test_gamma_sup_generator.sli
    | mpitests.test_gap_junctions_mpi.sli.mpitests/test_gap_junctions_mpi.sli
    | mpitests.test_get_nodes.sli.mpitests/test_get_nodes.sli
    | mpitests.test_ginzburg_neuron.sli.mpitests/test_ginzburg_neuron.sli
    | mpitests.test_global_rng.sli.mpitests/test_global_rng.sli
    | mpitests.test_iaf_ring.sli.mpitests/test_iaf_ring.sli
    | mpitests.test_localonly.sli.mpitests/test_localonly.sli
    | mpitests.test_mini_brunel_ps.sli.mpitests/test_mini_brunel_ps.sli
    | mpitests.test_mip_generator.sli.mpitests/test_mip_generator.sli
    | mpitests.test_neuron_vp.sli.mpitests/test_neuron_vp.sli
    | mpitests.test_neuron_vp_global.sli.mpitests/test_neuron_vp_global.sli
    | mpitests.test_noise_generator.sli.mpitests/test_noise_generator.sli
    | mpitests.test_one_to_one.sli.mpitests/test_one_to_one.sli
    | mpitests.test_pairwise_bernoulli.sli.mpitests/test_pairwise_bernoulli.sli
    | mpitests.test_parallel_conn_and_rand.sli.mpitests/test_parallel_conn_and_rand.sli
    | mpitests.test_poisson_generator.sli.mpitests/test_poisson_generator.sli
    | mpitests.test_poisson_generator_ps.sli.mpitests/test_poisson_generator_ps.sli
    | mpitests.test_pp_psc_delta.sli.mpitests/test_pp_psc_delta.sli
    | mpitests.test_ppd_sup_generator.sli.mpitests/test_ppd_sup_generator.sli
    | mpitests.test_pulsepacket_generator.sli.mpitests/test_pulsepacket_generator.sli
    | mpitests.test_rate_neurons_mpi.sli.mpitests/test_rate_neurons_mpi.sli
    | mpitests.test_sinusoidal_gamma_generator_1.sli.mpitests/test_sinusoidal_gamma_generator_1.sli
    | mpitests.test_sinusoidal_gamma_generator_2.sli.mpitests/test_sinusoidal_gamma_generator_2.sli
    | mpitests.test_sinusoidal_gamma_generator_3.sli.mpitests/test_sinusoidal_gamma_generator_3.sli
    | mpitests.test_sinusoidal_gamma_generator_4.sli.mpitests/test_sinusoidal_gamma_generator_4.sli
    | mpitests.test_sinusoidal_poisson_generator_1.sli.mpitests/test_sinusoidal_poisson_generator_1.sli
    | mpitests.test_sinusoidal_poisson_generator_2.sli.mpitests/test_sinusoidal_poisson_generator_2.sli
    | mpitests.test_sinusoidal_poisson_generator_3.sli.mpitests/test_sinusoidal_poisson_generator_3.sli
    | mpitests.test_sinusoidal_poisson_generator_4.sli.mpitests/test_sinusoidal_poisson_generator_4.sli
    | mpitests.test_symmetric_connections_mpi.sli.mpitests/test_symmetric_connections_mpi.sli
    | mpitests.ticket-400.sli.mpitests/ticket-400.sli
    | mpitests.ticket-516.sli.mpitests/ticket-516.sli
    | mpitests.ticket-955.sli.mpitests/ticket-955.sli
    | mpitests.topo_mpi_test_free_layer_to_layer_pairwise_bernoulli_on_source.sli.mpitests/topo_mpi_test_free_layer_to_layer_pairwise_bernoulli_on_source.sli
    | mpitests.topo_mpi_test_free_layer_to_layer_pairwise_bernoulli_on_target.sli.mpitests/topo_mpi_test_free_layer_to_layer_pairwise_bernoulli_on_target.sli
    | mpitests.topo_mpi_test_free_layer_to_layer_source_driven.sli.mpitests/topo_mpi_test_free_layer_to_layer_source_driven.sli
    | mpitests.topo_mpi_test_free_layer_to_layer_target_driven.sli.mpitests/topo_mpi_test_free_layer_to_layer_target_driven.sli
    | mpitests.topo_mpi_test_free_layer_to_sd_target_driven.sli.mpitests/topo_mpi_test_free_layer_to_sd_target_driven.sli
    | mpitests.topo_mpi_test_free_pg_to_layer_pairwise_bernoulli_on_source.sli.mpitests/topo_mpi_test_free_pg_to_layer_pairwise_bernoulli_on_source.sli
    | mpitests.topo_mpi_test_free_pg_to_layer_pairwise_bernoulli_on_target.sli.mpitests/topo_mpi_test_free_pg_to_layer_pairwise_bernoulli_on_target.sli
    | mpitests.topo_mpi_test_free_pg_to_layer_source_driven.sli.mpitests/topo_mpi_test_free_pg_to_layer_source_driven.sli
    | mpitests.topo_mpi_test_free_pg_to_layer_target_driven.sli.mpitests/topo_mpi_test_free_pg_to_layer_target_driven.sli
    | mpitests.topo_mpi_test_pairwise_bernoulli_on_source.sli.mpitests/topo_mpi_test_pairwise_bernoulli_on_source.sli
    | mpitests.topo_mpi_test_pairwise_bernoulli_on_target.sli.mpitests/topo_mpi_test_pairwise_bernoulli_on_target.sli

    Please report test failures by creating an issue at
        https://github.com/nest/nest_simulator/issues

----------------------------------------------------------------------
```

**Review by espenhgn — APPROVED** [review]

**Comment by heplesser** [comment]
@espenhgn Could you run the tests once more with `--oversubscribe` as additional option to `mpirun` in your `.nestrc` file? In my `.nestrc`,  it looks like this
```
/mpirun
[/integertype /stringtype /stringtype]
[/numproc     /executable /scriptfile]
{
 () [
  (mpirun --oversubscribe -np ) numproc cvs ( ) executable ( ) scriptfile
 ] {join} Fold
} Function def
```

Older MPI-versions were not strict about overuse, but now we need to fix this problem properly. I will create a new issue.

**Comment by heplesser** [comment]
> I tested merging this PR with master and it looks good to go.
> The Python test suite now completes without problems:
> 
> ```
> $ python -c "import nest; nest.test()"
> ...
> Ran 357 tests in 61.615s
> 
> OK (skipped=7)
> ```

@espenhgn Does it run the test that was previously skipped because of missing MPI4Py?

**Comment by espenhgn** [comment]
MPI tests ran successfully with the oversubscribe option. `test_connect_all_patterns.py` ran as well.

**Review by espenhgn — APPROVED** [review]
please merge

**Pull request merged**
