### PR TITLE
Update extension for API extractor

### PR DESCRIPTION
**Pull request by jessica-mitchell**
This PR modifies the `extract_api_functions.py` script so it no longer outputs an unneeded JSON file, and moves the parts of the script that were in conf.py into one file in `_ext`.

Here is [output](https://nest-simulator--2965.org.readthedocs.build/en/2965/ref_material/pynest_api/index.html) (no change should have occurred)

### CODE REVIEW

**Comment by jessica-mitchell** [comment]
@nicolossus @terhorstd I noticed that `isort` failed in the CI the first time even though when I committed it said it passed. I just ran `isort` on the file and that did the trick, but do you know why it would've passed on the commit initially? The error was only a new line missing.

**Comment by nicolossus** [comment]
> @nicolossus @terhorstd I noticed that `isort` failed in the CI the first time even though when I committed it said it passed. I just ran `isort` on the file and that did the trick, but do you know why it would've passed on the commit initially? The error was only a new line missing.

@jessica-mitchell Thanks for noticing! I have made a fix in https://github.com/nest/nest-simulator/pull/2968.

**Review by nicolossus — APPROVED** [review]
The PR looks good to me!

**Comment by jessica-mitchell** [comment]
Merging with 1 reviewer as its documentation

**Pull request merged**
