### PR TITLE
Add missing initialiser in copy constructor for stdp_nn_pre-centered_connection

### LINKED ISSUE #1435: Errors when trying to install NEST on Saga
Hello.
When trying to install NEST 2.20.0 on the Norwegian HPC Saga I get:
"There were errors detected during the run of the NEST test suite!"

Here's my install script:

module purge
module load GSL/2.6-GCC-8.3.0
module load Python/3.7.4-GCCcore-8.3.0
module load SciPy-bundle/2019.10-foss-2019b-Python-3.7.4
module load CMake/3.12.1
module list
cmake -DCMAKE_INSTALL_PREFIX=$HOME/nest-2.20.0 \
-Dwith-python=3 \
 ..
make -j
make install
make installcheck

I attach the report directory.
[reports.zip](https://github.com/nest/nest-simulator/files/4220619/reports.zip)

### PR DESCRIPTION
**Pull request by heplesser**
This fixes #1435.

@jasperalbers This should also go into 2.20.1.

### CODE REVIEW

**Comment by clinssen** [comment]
Great catch!

I am very disappointed that cppcheck does not catch this.
```
MSGBLD0155: [CPPC] [models/stdp_nn_pre-centered_connection.h:179]: (style) The function 'check_connection' is never used.
MSGBLD0155: [CPPC] [models/stdp_nn_pre-centered_connection.h:172]: (style) The function 'handles_test_event' is never used.
MSGBLD0155: [CPPC] [models/stdp_nn_pre-centered_connection.h:231]: (style) The function 'send' is never used.
MSGBLD0155: [CPPC] (information) Cppcheck cannot find all the include files (use --check-config for details)
MSGBLD0160: CPPCHECK for file ./models/stdp_nn_pre-centered_connection.h completed.
```

Do you suppose we should add Kplus member access to get_status() and set_status() as well, in the same model?

**Comment by heplesser** [comment]
> Do you suppose we should add Kplus member access to get_status() and set_status() as well, in the same model?

In principle yes, but I saw now that it is also inaccessible in, e.g., `stdp_connection`, so fixing this would be a bigger operation. Could you create a follow-up issue for that?

**Comment by heplesser** [comment]
@Ziaeemehr Could you check if the fix in this PR solves the problem for you as well?

**Comment by Ziaeemehr** [comment]
@heplesser  The PR solves the problem.
```sh
Phase 8: Running C++ tests (experimental)
-----------------------------------------
  Not running C++ tests because NEST was compiled without Boost.

NEST Testsuite Summary
----------------------
  NEST Executable: /home/abolfazl/prog/nest-build/bin/nest
  SLI Executable : /home/abolfazl/prog/nest-build/bin/sli
  Total number of tests: 870
     Passed: 860
     Skipped: 10 (9 PyNEST)
     Failed: 0 (0 PyNEST)

Built target installcheck
```

**Pull request merged**
