### PR TITLE
Refactor testsuite and move from nose to Pytest

### LINKED ISSUE #345: do_tests should get all arguments from the commandline
Currently, `do_tests.sh` is created from `do_tests.sh.in` by cmake. This means that several variables of the kind `@ARG@` are set fixed in the script, which makes it impossible to use the script for other installations and also makes the script itself more complex as it needs to be. The script should get all its arguments from the commandline instead.

This was known as trac393. See also #318.

### LINKED ISSUE #700: Suppress all NEST startup output
When running simulations on large systems the user should be able to minimize the amount of output NEST is generating during startup. At the moment, I see two issues

1. NEST's welcome message
2. INFO output from the rng manager

I would hence suggest two modifications:

1. add a verbosity check round the `welcome` and `shortwelcome` calls in sli-init (https://github.com/nest/nest-simulator/blob/master/lib/sli/sli-init.sli#L2141 ff), so that the verbosity level in .nestrc is respected
2. set the default verbosity to `M_ERROR` in the LoggingManager constructor (https://github.com/nest/nest-simulator/blob/master/nestkernel/logging_manager.cpp#L39)

I am uncertain about the second change, so I would ask @jougs @heplesser to comment on this. If you agree, I can have a PR ready in no time.

### LINKED ISSUE #972: `make installcheck` reaches wrong testing code after sourcing `nest_vars.sh` for a different version
Hi all,

I notice that when installing a given version of NEST using the usual routine:

```
rm -r bld
mkdir bld
cd bld
cmake ${SOURCE_DIR} -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR}
make
make install
make installcheck
```

... the testing suite that is used for the install checks is not that of the NEST version that was just built, but rather that of the NEST version referenced by the environment variables from `nest_vars.sh`.

This caused me quite some headaches as I was trying to install nest versions with different test suites although the same `nest_vars.sh` script had been sourced in my .zshrc the whole time..

Adding the line `source "${INSTALL_DIR}/bin/nest_vars.sh"` before `make installcheck` seems to solve the issue.

### LINKED ISSUE #1130: Phase 5 Tests all fail with ' Open MPI does not support recursive calls of mpirun'
I'm building `nest-stimulator` directly from a fork of the repo. things are largely working ok. I ran cmake with:

> cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/eric/nest_dev /home/eric/nest_dev/nest-simulator -Dwith-python=3 -Dwith-mpi=ON

While `make` and `make install` ran ok,  phase 5 of the tests (for mpi) all failed with something like:

> **********************************************************
> Open MPI does not support recursive calls of mpirun
> **********************************************************
> Feb 22 10:01:50 unittest::assert_or_die [Fatal]: 
>     Assertion failed: unittest::distributed_collect_assert_or_die: collected 
>     results.
> Feb 22 10:01:50 unittest::assert_or_die [Fatal]: 
>     Exiting with code 1.
> Failed: missed SLI assertion
> Running  /opt/nest/bin/sli /opt/nest/share/doc/nest/topology/mpitests/topo_mpi_test_divergent.sli
> SLI v2.16.0 (C) 2004 The NEST Initiative
> N_MPI: 1

I've attached TEST-core.phase_5.xml (note changed extension to `txt` otherwise it wouldn't let me attach). [TEST-core.phase_5.txt](https://github.com/nest/nest-simulator/files/2894640/TEST-core.phase_5.txt)

I am in Ubuntu 16/Python 3.7 (Anaconda) and have Open MPI 1.10.2.

### PR DESCRIPTION
**Pull request by jougs**
This PR refactors the test runner scripts of NEST and PyNEST and makes them independent of configuration-time variables previously replaced into the scripts.

Changes in detail:
* `do_tests.sh` now gets all paths and executables on the commandline (fixes #345).
* `nest_vars.sh` does not export paths anymore, that could have confused NEST(fixes #972).
   Now a separate PR: #1578
* Tests are now run in parallel with as many processors as are available (kudos to @terhorstd).
* Test results from SLI tests are not written as JUnit/XML anymore.
* The info output from the `RandomManager` initialization is gone (fixes #700 and #415).
   Now a separate PR: #1577
* The PyNEST testsuite was
   * moved outside of the `nest` module directory
   * converted to using `pytest` instead of `nosetests`
   * modified so that PyNEST tests do not include MPI anymore (fixes #1130).
* Increased legibility by adding an informative header and removing redundant paths from the testsuite printouts.

---
This replaces #1071, but with base branch nest-3 instead of master.

### CODE REVIEW

**Comment by heplesser** [comment]
@jougs Great work! The test output already looks so much better, and the configuration information at the beginning of the test execution will allow us to support users experiencing failing test much better. I have a few questions and comments:

1. If I understand the test output on Travis right, where up to 2 tests are run in parallel, then there are two output lines for each test, one "Running test_xyz" and one "test_xyz ... Success", but the order of lines for different tests is somewhat unpredictable due to parallel execution. Do we really need the first ("Running ...") line?
1. If tests should fail, will the summary at then end report which tests failed, so one no longer would have to scroll back and search for the failing test?
1. Could we make the maximum number of tests run in parallel configurable, e.g., through a variable in `.nestrc`? This may be useful when running the testsuite on a system used for interactive work.

**Comment by hakonsbm** [comment]
@jougs Nice, this looks a lot better! I have a few remarks though:

1. Running the testsuite on my computer reports 7 failing PyNEST tests. However it is not clear which tests are failing (by process of elimination it should be the seven listed PyNEST MPI tests, but this isn't stated).
1. Should every PyNEST test be listed (instead of dots), to keep output consistent with the SLI tests?
1. Regarding @heplesser's second point, failing tests are not reported at the end of the testsuite. This would be a useful addition.
1. The C++ test phase isn't run. I have compiled with Boost, and the `run_all_cpptests` file is created, but it says `Not running C++ tests because NEST was compiled without Boost`.
1. The todos in the C++ test phase should probably be fixed. I have some work on this in a stash, so I can fix the todos and make a PR towards your branch.

**Comment by jougs** [comment]
@heplesser: Thanks for the praise and your suggestions. I'm very open to implement them.

First, I'd like to get it working, though! Could you maybe help out with the problems on Mac? Apparently @terhorstd's solution for getting the number of available processors via `/proc` and system information using `uname` is not very portable.

**Comment by lekshmideepu** [comment]
@jougs  :  sysctl -a | grep machdep.cpu

**Comment by Silmathoron** [comment]
Just noticed the commit text and came to provide a bit of psychological support!
Cheers <3
(maybe take a break and then come back to it later? ^^)

**Comment by jougs** [comment]
# :heart_eyes:
Thank you so much! This is really a total mess. Everything's running fine locally, while it fails on Travis. And the debugging sessions I can get there are way too short to hunt the problem down. Argh!

**Comment by jougs** [comment]
I'm closing this, as this got way too messy. The code was/will be made into multiple smaller PRs.

**Comment by jougs** [comment]
For a detailed list of which issue was fixed in which PR, see https://github.com/nest/nest-simulator/pull/1071#issuecomment-762513312

**Pull request closed without merging**
