### PR TITLE
Backport of #1718 to 2.20.1

### PR DESCRIPTION
**Pull request by hakonsbm**

### CODE REVIEW

**Comment by heplesser** [comment]
Pure backport, therefore merging without review.

**Comment by jougs** [comment]
The build failures on Travis are most likely gone, once #1736 is merged into the `nest-2.10.1` branch and you have pulled the changes here.

**Comment by hakonsbm** [comment]
@jougs After pulling in master with the #1623 backport, there's another issue with Travis. Looks like it's a more general PyNEST installation problem.

**Comment by jougs** [comment]
Merging, as the Travis problems seem to be gone.

**Pull request merged**
