### PR TITLE
Update .gitignore with CTestTestfile.cmake and files generated by Doxygen

### PR DESCRIPTION
**Pull request by jd41**
I got several untracked files that were apparently generated by cmake/when building the Doxygen documentation. This patch adds them to .gitignore.

### CODE REVIEW

**Comment by terhorstd** [comment]
This should probably not go here. The underlying problem that needs to be solved is #1629 , ignoring what is wrong isn't a good solution.

**Comment by jd41** [comment]
The CTestTestfile.cmake files seem to be generated just by running cmake
for compiling nest, without making the Doxygen/Sphinx documentation.

**Comment by jd41** [comment]
In fact, this seems to be true for CMakeDoxyfile.in and
CMakeDoxygenDefaults.cmake as well.

I get the following after running cmake on a clean source:
        CMakeDoxyfile.in
        CMakeDoxygenDefaults.cmake
        CTestTestfile.cmake
        doc/CTestTestfile.cmake
        examples/CTestTestfile.cmake
        extras/CTestTestfile.cmake
        extras/ConnPlotter/CTestTestfile.cmake
        lib/CTestTestfile.cmake
        libnestutil/CTestTestfile.cmake
        librandom/CTestTestfile.cmake
        models/CTestTestfile.cmake
        nest/CTestTestfile.cmake
        nestkernel/CTestTestfile.cmake
        precise/CTestTestfile.cmake
        pynest/CTestTestfile.cmake
        sli/CTestTestfile.cmake
        testsuite/CTestTestfile.cmake
        testsuite/cpptests/CTestTestfile.cmake
        testsuite/mpi_selftests/fail/CTestTestfile.cmake
        testsuite/mpi_selftests/pass/CTestTestfile.cmake
        testsuite/mpitests/CTestTestfile.cmake
        testsuite/musictests/CTestTestfile.cmake
        testsuite/regressiontests/CTestTestfile.cmake
        testsuite/selftests/CTestTestfile.cmake
        testsuite/unittests/CTestTestfile.cmake
        topology/CTestTestfile.cmake


2020-06-10 13:45 GMT+02:00, Joris Dolderer <jolderer@gmail.com>:
> The CTestTestfile.cmake files seem to be generated just by running cmake
> for compiling nest, without making the Doxygen/Sphinx documentation.
>

**Comment by jd41** [comment]
Furthermore, the cmake command apparently modifies doc/Makefile as well.

Full output after running cmake in a fresh repository clone:

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   doc/Makefile

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        CMakeDoxyfile.in
        CMakeDoxygenDefaults.cmake
        CTestTestfile.cmake
        doc/CTestTestfile.cmake
        examples/CTestTestfile.cmake
        extras/CTestTestfile.cmake
        extras/ConnPlotter/CTestTestfile.cmake
        lib/CTestTestfile.cmake
        libnestutil/CTestTestfile.cmake
        librandom/CTestTestfile.cmake
        models/CTestTestfile.cmake
        nest/CTestTestfile.cmake
        nestkernel/CTestTestfile.cmake
        precise/CTestTestfile.cmake
        pynest/CTestTestfile.cmake
        sli/CTestTestfile.cmake
        testsuite/CTestTestfile.cmake
        testsuite/cpptests/CTestTestfile.cmake
        testsuite/mpi_selftests/fail/CTestTestfile.cmake
        testsuite/mpi_selftests/pass/CTestTestfile.cmake
        testsuite/mpitests/CTestTestfile.cmake
        testsuite/musictests/CTestTestfile.cmake
        testsuite/regressiontests/CTestTestfile.cmake
        testsuite/selftests/CTestTestfile.cmake
        testsuite/unittests/CTestTestfile.cmake
        topology/CTestTestfile.cmake


2020-06-10 13:48 GMT+02:00, Joris Dolderer <jolderer@gmail.com>:
> In fact, this seems to be true for CMakeDoxyfile.in and
> CMakeDoxygenDefaults.cmake as well.
>
> I get the following after running cmake on a clean source:
>         CMakeDoxyfile.in
>         CMakeDoxygenDefaults.cmake
>         CTestTestfile.cmake
>         doc/CTestTestfile.cmake
>         examples/CTestTestfile.cmake
>         extras/CTestTestfile.cmake
>         extras/ConnPlotter/CTestTestfile.cmake
>         lib/CTestTestfile.cmake
>         libnestutil/CTestTestfile.cmake
>         librandom/CTestTestfile.cmake
>         models/CTestTestfile.cmake
>         nest/CTestTestfile.cmake
>         nestkernel/CTestTestfile.cmake
>         precise/CTestTestfile.cmake
>         pynest/CTestTestfile.cmake
>         sli/CTestTestfile.cmake
>         testsuite/CTestTestfile.cmake
>         testsuite/cpptests/CTestTestfile.cmake
>         testsuite/mpi_selftests/fail/CTestTestfile.cmake
>         testsuite/mpi_selftests/pass/CTestTestfile.cmake
>         testsuite/mpitests/CTestTestfile.cmake
>         testsuite/musictests/CTestTestfile.cmake
>         testsuite/regressiontests/CTestTestfile.cmake
>         testsuite/selftests/CTestTestfile.cmake
>         testsuite/unittests/CTestTestfile.cmake
>         topology/CTestTestfile.cmake
>
>
> 2020-06-10 13:45 GMT+02:00, Joris Dolderer <jolderer@gmail.com>:
>> The CTestTestfile.cmake files seem to be generated just by running cmake
>> for compiling nest, without making the Doxygen/Sphinx documentation.
>>

**Pull request closed without merging**
