### PR TITLE
Add detailed timers for gathering and delivering secondary events

### PR DESCRIPTION
**Pull request by heplesser**
This PR adds detailed timers that measure time used to gather and deliver secondary events in the same way as gathering and delivering spike is measured.

### CODE REVIEW

**Review by ackurth — APPROVED** [review]
This looks good to me!

**Comment by HanjiaJiang** [comment]
Thank you for the pull request. I have tested the code with network models with secondary events. The result shows that the new timers can indeed account for a previously unknown part of simulation time in such models.

**Comment by heplesser** [comment]
> Thank you for the pull request. I have tested the code with network models with secondary events. The result shows that the new timers can indeed account for a previously unknown part of simulation time in such models.

Excellent. Could you then formally approve the PR so I can merge it?

**Review by HanjiaJiang — APPROVED** [review]
The code looks very nice to me. Thank you!

**Pull request merged**
