### PR TITLE
Add link to 3.7 whats new page in docs

### PR DESCRIPTION
**Pull request by jessica-mitchell**
Make 3.7 link available for release

### CODE REVIEW

**Comment by jessica-mitchell** [comment]
@heplesser @terhorstd Are there any other key changes  we want to inform users about in the what's new section for 3.7? 
Here is what we have so far: https://nest-simulator--3153.org.readthedocs.build/en/3153/whats_new/v3.7/index.html#release-3-7

**Comment by heplesser** [comment]
@jessica-mitchell I would suggest to add the following new models/features
- #2971 
- #2987 
- #2960 

Also, once merged, we should mention the new interface for extension modules, this is a breaking change:
- #3103
- #3149

**Comment by jessica-mitchell** [comment]
> 
> Also, once merged, we should mention the new interface for extension modules, this is a breaking change:
> 
>     * [Create NEST Extension Interface for NEST compatible with new registration scheme and unloading #3103](https://github.com/nest/nest-simulator/pull/3103)
> 
>     * [Move registration of ConnBuilders, Backends, growth curves from nestmodule to respective managers, allowing unloading #3149](https://github.com/nest/nest-simulator/pull/3149)

I see changes to code but nothing really to the documentation for the nest-extension module - what does the user need to know about these changes? What does the user need to do differently?

**Comment by jessica-mitchell** [comment]
@heplesser ping!

**Comment by jessica-mitchell** [comment]
Merging as discussed at hackathon

**Pull request merged**
