### PR TITLE
Remove Connplotter from the NEST code base

### LINKED ISSUE #1971: Move ConnPlotter from NEST code base to separate package
The ConnPlotter packages included in the NEST code base is not an integral part of NEST, just an additional tool. I suggest to remove it from the NEST code base and turn it into an independent Python package hosted under github.com/nest.

@jougs @terhorstd Any comments?

### PR DESCRIPTION
**Pull request by pnbabu**
Fixes #1971 

This PR removes the files related to `ConnPlotter` and are now moved to a new repository [nest-connplotter](https://github.com/nest/nest-connplotter).

The PR in the `nest-connplotter` repo with the initial changes - https://github.com/nest/nest-connplotter/pull/1

### CODE REVIEW

**Review by jougs — APPROVED** [review]
LGTM!

**Review by heplesser — CHANGES_REQUESTED** [review]
Fine in principle, but I would not want to merge this before connplotter#1 is merged, so the ConnPlotter remains available at all times. Also, assuming that this will go into 3.1, the 3.0->3.1 transition guide should mention where ConnPlotter can now be found.

**Comment by jougs** [comment]
@pnbabu: can you please add a file `doc/userdoc/release_notes/v3.2/index.rst` along the lines of the 3.1 release notes and mention the move there as @heplesser suggested? Thanks!

**Comment by jougs** [comment]
@pnbabu: friendly ping!

**Comment by jougs** [comment]
@poojanbabu: You can re-use the introductory text from [my 3.2 release notes from #2208](https://github.com/nest/nest-simulator/pull/2208/files#diff-6be5a8306fdfd7edbc254cf36d2858491dc7272269ab026781a938a02bf131ea) for this one. If you're quick, I'll get to deal with the merge conflicts :wink:

**Comment by clinssen** [comment]
Can we link to the new repository from the documentation somewhere?

**Comment by jougs** [comment]
@pnbabu: the merge of #2200 apparently got you some conflicts. Can you please update. Thanks!

**Comment by jougs** [comment]
@pnbabu: thanks for the update!

I think @clinssen is right. Can you maybe add a link to the [related projects](https://nest-simulator.readthedocs.io/en/v3.1/related_projects.html) page and possibly also a paragraph with one image or so to the end of the [connection management](https://nest-simulator.readthedocs.io/en/v3.1/guides/connection_management.html) guide? You could also coordinate with @jessica-mitchell, who is anyway currently restructuring the guides and pages. Thanks!

**Comment by pnbabu** [comment]
@jougs I have added `conplotter` repository details to the [related projects](https://nest-simulator.readthedocs.io/en/v3.1/related_projects.html) page. It turns out that the existing example file in the `connplotter` repository is buggy and fixing it is taking longer than I expected. So I suggest we go ahead merging this PR and I will add the details to the `connection management` guide in a separate PR once I fix the bugs and have some figures.

**Review by heplesser — APPROVED** [review]
@pnbabu  Thank you for taking care of this!

**Pull request merged**
