### PR TITLE
Fix parentheses in connection_helpers 

### PR DESCRIPTION
**Pull request by aserenko**
The reason of Issue #3337 seems to be just forgotten parentheses.

### CODE REVIEW

**Review by gtrensch — APPROVED** [review]
Joint review. Looks good to us. Thanks for your contribution! 👍

**Comment by terhorstd** [comment]
Hi Alex, I fixed the formatting for Black. This is automatically done if you start to use the `pre-commit` setup which was recently added. Have a look [here](https://nest-simulator.readthedocs.io/en/stable/developer_space/guidelines/coding_guidelines_check.html#pre-commit), it really makes development easier.

**Comment by terhorstd** [comment]
The unrelated warnings of pylint are handled in #3339 .

**Review by clinssen — APPROVED** [review]
Cheers!

**Pull request merged**
