### PR TITLE
changed dynamic imports using exec to static imports

### PR DESCRIPTION
**Pull request by clinssen**
This addresses https://github.com/nest/nest-simulator/issues/564

### CODE REVIEW

**Comment by terhorstd** [comment]
this one is related to #1058 and should be checked for compatibility

**Comment by jougs** [comment]
Is Topology still working with this fix in place? The reason for the dynamic import was to support extension modules that install an optional Python component. I don't see how they'd be working with a purely static import.

**Comment by clinssen** [comment]
Abandoning this PR due to on-point issues raised by @jougs! 

We could potentially switch to a static import of the existing api files and a dynamic import in a special directory containing only user modules, but this is probably better handled later/as part of a different PR, because of active refactoring in PyNEST.

**Comment by babsey** [comment]
> static import of the existing api files and a dynamic import in a special directory containing only user modules

I like the idea of having static and dynamic imports.

**Comment by apeyser** [comment]
It shouldn't be exec, but it shouldn't be static either, but should use importlib module (which probably doesn't fix PyCharm, but it's still cleaner than this).

Should be a different PR on this.

**Pull request closed without merging**
