### PR TITLE
Documentation of exact integration for nest-simulator site [ci skip]

### PR DESCRIPTION
**Pull request by ingablundell**
This is just documentation!
This ipython notebook briefly describes exact integration.
@steffengraber This is documentation for the nest-simulator site.
I propose @jougs @heplesser as reviewers

### CODE REVIEW

**Comment by heplesser** [comment]
@ingablundell Thank you for writing this up! Could you add a section with an explicit example, e.g., the `iaf_psc_alpha` neuron with two indepedent alpha-function inputs (two different time constants). To really allow readers to connect math and code, it would be great if you would then also relate the equations to their implementation in NEST.

**Comment by ingablundell** [comment]
OK. I will add the example and try to relate code to math but that will make the documentation more complicated and more difficult to understand:)

**Comment by jougs** [comment]
@steffengraber: can you please check how/if this could be reformatted as a "normal" markdown file for the documentation? Thanks!

**Comment by steffengraber** [comment]
@jougs @ingablundell 

we can use ipython nbconvert for this:

`ipython nbconvert --to markdown notebook.ipynb`
`ipython nbconvert --to html notebook.ipynb`

Looks nice for me.

**Comment by ingablundell** [comment]
@heplesser I have now added a part with the iaf_psc_alpha as an example

**Comment by heplesser** [comment]
:+1: from me, @jougs, are you happy as well?

**Comment by jougs** [comment]
@ingablundell: nice work indeed!

Can you please still do the following things?
- rename the directory `exact_integration` to `ipynb`
- rename the file `Whatisexactintegration.ipynb`
 to `exact-integration.ipynb`in order comply to our [conventions](https://github.com/nest/nest-simulator/blob/master/extras/userdoc/md/documentation/README.md)
- change the headline to something like "Integrating neural models using exact integration"
- Rotter and Diesmann should be linked to http://dx.doi.org/10.1007/s004220050570

**Comment by ingablundell** [comment]
@jougs 

Yes, and I have done so.

**Comment by jougs** [comment]
Looks good now. Many thanks! :+1: and merging.

**Pull request merged**
