### PR TITLE
Fix issue #156: At Network reset, initialize music_in_portlist_ from …

### PR DESCRIPTION
**Pull request by mdjurfeldt**
…a stored pristine copy instead of clearing it

### CODE REVIEW

**Comment by jougs** [comment]
This change looks good to me, so :+1:. Maybe @tammoippen can have a second look? Do we need a test to prevent this problem from happening again?

**Comment by apeyser** [comment]
Maybe the comment for register_music_in_port could be a bit more expansive? If I were looking at this for the first time, I'd be confused about what 'pristine' is, and why you would want to set it this way.  So something about this being the default reset under certain conditions.

**Comment by mdjurfeldt** [comment]
Better now? :)

**Comment by jougs** [comment]
:+1: once my comments have been addressed.

**Comment by mdjurfeldt** [comment]
Done!

**Comment by apeyser** [comment]
Solves my request re comments

**Pull request merged**
