### PR TITLE
Fix location for 'spatial' headers

### PR DESCRIPTION
**Pull request by jougs**
This fixes a problem where the header files under `spatial` have not been found when linking them from extension modules. The fix for now is to move the files to the `nestkernel` directory directly and postpone restructuring of that directory. As this is an emergency fix that only moves files around without touching actual code, I'm only nominating a single reviewer for sanity checking.

This is a follow-up to #1748.

### CODE REVIEW

**Comment by clinssen** [comment]
Thinking back to @terhorstd's between-headers dependency analysis of the ``nestkernel`` directory at the recent hackathon, wasn't the ``spatial`` subdirectory mostly (and almost perfectly) the only self-contained section of the nestkernel sources? If we are considering moving towards more subdirectories in the ``nestkernel`` directory, not fewer, then perhaps we could use something like the following CMake code instead of removing the directory as a temporary measure:

```cmake
function( FILTER_HEADERS2 in_list out_list )
    set( tmp_list ${in_list} )
    list( FILTER tmp_list EXCLUDE REGEX "^.*spatial.*$")
    set( ${out_list} ${tmp_list} PARENT_SCOPE )
endfunction ()

FILTER_HEADERS("${nestkernel_sources}" install_headers )
FILTER_HEADERS2("${install_headers}" install_headers )
install( FILES ${install_headers}
         DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/nest )

install( DIRECTORY "${CMAKE_SOURCE_DIR}/nestkernel/spatial"
         DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/nest )
```

This comes at the end of ``nestkernel/CMakeLists.txt``.

The "spatial" files have to be explicitly excluded using the FILTER_HEADERS2 function, because the CMake script builds a long list of *all* source files, and the subdirectory is lost when they are copied. So we first exclude them from the regular ``install( FILES ...)`` and copy them separately using an ``install( DIRECTORY ...)``. A better solution would loop over a list containing, for now, the string "spatial" as the only element (but to which other subdirectories could be added).

**Comment by clinssen** [comment]
Fixes #1790.

**Comment by clinssen** [comment]
Related issue that was closed earlier as "wontfix": https://github.com/nest/nest-simulator/issues/1175

Perhaps discussion on the ``nestkernel`` directory layout organisation could take place there after this PR is merged.

**Review by hakonsbm — APPROVED** [review]
Looks fine as an emergency fix.

**Pull request merged**
